### ISSUE TITLE
`Mapping` deprecated Python 3.10

### ISSUE THREAD

**Issue by natolambert** [lvwerra/trl#104]
https://github.com/lvwerra/trl/blob/11ac2638c037d8a3b579636fd6a556610b1c161c/trl/core.py#L13-L25

this function should be updated, not sure what it's used for yet, but FYI.

**Comment by lvwerra** [comment]
Thanks! It's just a utility function to flatten nested dicts for logging.

**Comment by natolambert** [comment]
fixed in #112
