### ISSUE TITLE
Segfault when trying out code example on the README.md

### ISSUE THREAD

**Issue by zitterbewegung** [lvwerra/trl#12]
I get a segfault when trying out the code on the README.md.

# get models
gpt2_model = GPT2HeadWithValueModel.from_pretrained('gpt2')
gpt2_model_ref = GPT2HeadWithValueModel.from_pretrained('gpt2')
gpt2_tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

**Comment by lvwerra** [comment]
Hi @zitterbewegung 
Could you share the stack trace? Has the machine access to the internet?

**Comment by zitterbewegung** [comment]
The weird part is that this collab notebook won't crash
https://colab.research.google.com/drive/1GE_riqtg4EiRt7BuAsrzKwTNDUIXCRMZ?usp=sharing

**Comment by zitterbewegung** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  TITAN RTX           On   | 00000000:0B:00.0  On |                  N/A |
| 41%   35C    P8    15W / 280W |    361MiB / 24219MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2878      G   /usr/lib/xorg/Xorg                199MiB |
|    0   N/A  N/A      3206      G   /usr/bin/gnome-shell              156MiB |
|    0   N/A  N/A    102465      G   /usr/lib/firefox/firefox            3MiB |
+-----------------------------------------------------------------------------+

**Comment by zitterbewegung** [comment]
There was no stack trace and the machine had access to the internet

**Comment by lvwerra** [comment]
How exactly did the code break? You did not get any error at all? This part of the code is not `trl` specific so it might be a `transformers` library issue. Have you tried just loading the tokenizer?

**Comment by zitterbewegung** [comment]
I setup my environment on ubuntu 20.04 and also on AWS sagemaker using
pytorch with python 3.6. I only get the error [segmentation fault]. Would
it be safe to use a more recent version of transformers?

**Comment by lvwerra** [comment]
I don't quite get what the `segmentation fault` is. Is that a AWS specific error or is it a Python error? If it is a Python error could you share the full error message? Loading pretrained models is possible in `transformers==2.6.0` but you could try to be sure. However, there are issues with the `trl` libraries in more recent versions (see #9).

**Comment by lvwerra** [comment]
It could be related to this: https://github.com/huggingface/transformers/issues/4857

**Comment by zitterbewegung** [comment]
Okay I’ll try that

**Comment by zitterbewegung** [comment]
Needed to use requirements.txt in a virtualenv instead of conda
