### ISSUE TITLE
Cliprange parameter unintuitive name

### ISSUE THREAD

**Issue by natolambert** [lvwerra/trl#122]
~You can see [here](https://github.com/lvwerra/trl/blob/d2e8bcf8373726fb92d2110c500f7df6d0bd566d/trl/trainer/ppo_config.py#L46) that cliprange is a float, but maybe should be a bool or removed entirely?~

I see that this variable is for the loss clamp, maybe we can name it that?

**Comment by lvwerra** [comment]
Closing this for now as we decided not to rename for now :)
