### ISSUE TITLE
Works for T5/BART?

### ISSUE THREAD

**Issue by danyaljj** [lvwerra/trl#13]
Very cool work! 

Does this work for T5/BART models as well?

**Comment by danyaljj** [comment]
Side note: it'd be good to update the `transformers` dependency to the latest (v4.0.0).

**Comment by lvwerra** [comment]
You are right, when I have time I'll upgrade it to v4.0.0. I haven't tested it but I suspect if you take a model with a text generation head it should work. Note that you need add a value head to your model architecture (see [here](https://github.com/lvwerra/trl/blob/master/trl/gpt2.py)).

**Comment by danyaljj** [comment]
I can try it. Other than running with no errors, what other ways I can test that the code is working fine? Is there a benchmark or a quantitative way of verifying the code?

**Comment by lvwerra** [comment]
Monitoring the rewards on the IMDb dataset would be a good start. For GPT-2 it takes only 1-2h to train.

**Comment by minbeomkim** [comment]
Could you introduce any progress in BART with TRL???
