### ISSUE TITLE
error about self.accelerator.backward(loss)

### ISSUE THREAD

**Issue by cdxzyc** [lvwerra/trl#130]
During training, the following error is reported at code `self.accelerator.backward(loss)` in `train_minibatch`

> RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

After I add `retain_graph=True`, the code can run normally, is this normal or am I doing something wrong?

**Comment by younesbelkada** [comment]
Hi @cdxzyc 
Thanks for the issue! I suspect there is something wrong with your training loop
Can you share with us how you are training your model using the Trainer?
Thanks
