### ISSUE TITLE
how to use these model for inferencing 

### ISSUE THREAD

**Issue by sainathpawar** [lvwerra/trl#135]
I follow these notebooks https://github.com/lvwerra/trl/blob/main/examples/sentiment/notebooks/gpt2-sentiment-control.ipynb
So once the model is saved locally.  how we can use these for inferencing.
Can we have a notebook to showcase?

**Comment by lvwerra** [comment]
Hi @sainathpawar, you should be able to use the saved models directly in `transformers`. See this section in the docs: https://huggingface.co/docs/trl/quickstart#how-to-use-a-trained-model

**Comment by lvwerra** [comment]
Closing this for now, feel free to re-open if there are any follow-up questions!
