### ISSUE TITLE
Exposing the hyper-parameters of the optimzation 

### ISSUE THREAD

**Issue by danyaljj** [lvwerra/trl#14]
It looks like there are a bunch of hyperparameters in the original work that could be tweaked. 
For instance beta parameter (Eq.2 of https://arxiv.org/pdf/1909.08593.pdf). 
Would be nice to have an easy way to set/change such parameters.

**Comment by lvwerra** [comment]
Hi! You can actually control these parameters. Later in the paper they also talk about dynamically adjusting beta. You can control this through the keyword arguments `"adap_kl_ctrl"` and `"init_kl_coef"` when initialising the `PPOTrainer`. You can also adjust the target KL-divergence through `"target"` and the windowing through `"horizon"` as well as all the PPO parameters.
