### ISSUE TITLE
EleutherAI/gpt-j-6B , Can this model be used instead of t5 or gpt2 for  CODE GENERATION 

### ISSUE THREAD

**Issue by Sid22kiara** [lvwerra/trl#141]
I am trying to run the file t5-sentiment.py , instead of model t5 can i replace this with   will it work the same.

**Comment by lvwerra** [comment]
If you are running a decoder model I would look at `gpt2-sentiment.py`. Note that usually it is good to start with a smaller model. In general your format seems good, i guess you need to define a reward function as well.

**Comment by Sid22kiara** [comment]
Hey @lvwerra is it better to use trl or trlx library , for GPT J model , its 6B parameter .

Reward function , what should it looks for code like below 

eg . # This program adds two numbers

num1 = 1.5
num2 = 6.3

# Add two numbers
sum = num1 + num2

# Display the sum
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

How will i be writing a reward fuction , what things to have in my mind when writing .
please help

**Comment by Sid22kiara** [comment]
ok

**Comment by lvwerra** [comment]
Closing for now, feel free to reopen if you run into any issues.
