### ISSUE TITLE
Slight issues in the example notebook

### ISSUE THREAD

**Issue by BirgerMoell** [lvwerra/trl#150]
I noticed some minor things in the example colab notebook. 

Installs where not properly setup and you needed to initialise wandb.
I made a notebook with the necessary changes if it would be useful.
https://colab.research.google.com/github/lvwerra/trl/blob/main/examples/sentiment/notebooks/gpt2-sentiment.ipynb

It was basically one cell with

`!pip install transformers trl wandb`

and one with 

```
import wandb
wandb.init()
```

**Comment by younesbelkada** [comment]
Hi @BirgerMoell 
Nice catch! These cells are missing indeed, would you mind opening a PR to fix this? it will be a nice contribution!

**Comment by BirgerMoell** [comment]
@younesbelkada made a PR. I noticed that some installs was added to the input (just the output of me running it). I'm not sure if these are shown when you load the notebook. If you want me to clean it up I'll fix that too.
https://github.com/lvwerra/trl/pull/158

**Comment by lvwerra** [comment]
I think this was fixed in https://github.com/lvwerra/trl/pull/159.
