### ISSUE TITLE
Question about why vpred and values[i] are different

### ISSUE THREAD

**Issue by scarydemon2** [lvwerra/trl#161]
Hi，
Thanks for providing this great library! And I'm trying to understand.
When I read the code, I was confused that for the i-th instance, the vpred and values[i] are different but the 'input_ids' and 'decoder_input_ids' of vpred and values[i] are the same and even the 'last_hidden_state' of them is the same. So why does the 'v_head' of the same model have different outputs for the same input?

**Comment by lvwerra** [comment]
We are doing several optimization steps on the model chaning its weights inside `step` so the initial value the model predicts (`values`) might change from the values shown in the following steps (`vpreds`). I agree the naming is not super intuitive :)
