### ISSUE TITLE
Wandb - Selected runs are not logging media for the key objective/*, but instead are logging values of type list.

### ISSUE THREAD

**Issue by gjmulder** [lvwerra/trl#164]
![objective_logprobs](https://user-images.githubusercontent.com/10833500/220044821-9ca04df7-49a7-4f79-a951-c65060f682ce.png)

Getting this error in wandb when running either:

```
./examples/sentiment/scripts/gpt2-sentiment.py
./examples/sentiment/scripts/t5-sentiment.py
```
It looks like the data are lists of tensors. From the TRL Showcase it should be displaying histograms?

EDIT: I'm using accelerate across 4 GPUs, but the lists look to be of length 256, which at a guess is the batch size?

**Comment by lvwerra** [comment]
Yes, usually list of tensors are converted to histograms automatically (see rewards or ratios). Not sure what happened there but if you want to take a look that would be much appreciated.

**Comment by gjmulder** [comment]
I'm not too familiar with Wandb, so I had wondered if it could handle a list of tensors. `env/reward_dist` is rendering correctly as a histogram which is what made me suspect that tensors weren't supported.

**Comment by younesbelkada** [comment]
Managed to reproduce the issue when looking at the logs logged out, if you login to your wandb account the bug should disappear
