### ISSUE TITLE
Conflict in requirements.txt packages

### ISSUE THREAD

**Issue by abhishek0318** [lvwerra/trl#17]
`pip install -r requirements.txt` gives the following error. This can be fixed by changing to tqdm version to 4.47.0.

```
The conflict is caused by:
    The user requested tqdm==4.43.0
    simpletransformers 0.60.9 depends on tqdm>=4.47.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by lvwerra** [comment]
Interesting - must be an issue with the newer verisons of `pip`. Will likely drop the dependency to `simpletransformers` in the next release.

**Comment by lvwerra** [comment]
Dropped `simpletransformers` requirement in #25.
