### ISSUE TITLE
Question in the tutorial

### ISSUE THREAD

**Issue by shizhediao** [lvwerra/trl#174]
In the [tutorial](https://colab.research.google.com/github/lvwerra/trl/blob/main/examples/sentiment/notebooks/gpt2-sentiment.ipynb#scrollTo=LG-PC60LURQL)
I could not find the `tokens` in the `df_batch` during the model inspection.

`query_tensors = df_batch['tokens'].tolist()`

**Comment by shizhediao** [comment]
I think it should be 
`query_tensors = df_batch['input_ids'].tolist()`

**Comment by lvwerra** [comment]
I just checked and indeed it should be `input_ids`. Do you want to open a PR? Otherwise I can do it later.

**Comment by shizhediao** [comment]
I am going to open a PR right now. Thanks for your confirmation!

**Comment by shizhediao** [comment]
hi I have opened a PR #175.
