### ISSUE TITLE
Cannot install trl

### ISSUE THREAD

**Issue by Jiayi079** [lvwerra/trl#179]
I'm having an error when I try to install trl

C:\Users\evagu>pip install trl
Collecting trl
  Using cached trl-0.2.1-py3-none-any.whl (38 kB)
  Using cached trl-0.2.0-py3-none-any.whl (38 kB)
  Using cached trl-0.1.0-py3-none-any.whl (16 kB)
  Using cached trl-0.0.3-py3-none-any.whl (15 kB)
  Using cached trl-0.0.2-py3-none-any.whl (15 kB)
  Using cached trl-0.0.1-py3-none-any.whl (15 kB)
ERROR: Cannot install trl==0.0.1, trl==0.0.2, trl==0.0.3, trl==0.1.0, trl==0.2.0 and trl==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    trl 0.2.1 depends on torch>=1.4.0
    trl 0.2.0 depends on torch>=1.4.0
    trl 0.1.0 depends on torch>=1.4.0
    trl 0.0.3 depends on torch>=1.4.0
    trl 0.0.2 depends on torch>=1.4.0
    trl 0.0.1 depends on torch>=1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Jiayi079** [comment]
Hello @younesbelkada ,
Thank you so much for your quick response! I found the reason why is that I'm using python 3.11 which is too new to install torch. BTW, thanks!

**Comment by younesbelkada** [comment]
Thanks so much! Thanks for the report, we'll have a look about that, so you're saying that torch cannot be installed under `python=3.11` ?

**Comment by Jiayi079** [comment]
yes, I think so. I download `python 3.8` and everything can work. I searched online and it shows that torch can only be installed under **python 3.7~3.9**

**Comment by younesbelkada** [comment]
Sounds good! Thanks a lot, therefore the solution is to use python < 3.11 for now until this will be resolved on `torch` side
Happy TRL-ing!
