### ISSUE TITLE
adap_kl_ctrl boolean is not used 

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [lvwerra/trl#18]
Hello,

Thanks for this implementation, is it possible that your kl adaptation is always on ?
https://github.com/lvwerra/trl/blob/750f5fd5329bb81c79b00243c4c8923ac14981d5/trl/ppo.py#L92

Best,
Thibaud

**Comment by lvwerra** [comment]
Yes, that is true - well spotted! I'll add it as a TODO.
