### ISSUE TITLE
Wondering why it takes so long to train a step

### ISSUE THREAD

**Issue by tuzeao** [lvwerra/trl#188]
After running the sample code scrpts/gpt2-sentiment.py(https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt2-sentiment.py), it works well fine, except one thing I am curious: is it normal  to take around 90 seconds to train a batch? 
Continually, I printed the detail time cost and found that the "Run PPO step" cost the most time, about 58 seconds. So what is it exactly doing to cost so much time? I know about it's general workflow in README.md

**Comment by lvwerra** [comment]
This is the part where the model is optimized with PPO so several forward/backward passes and optimizations steps are run.

**Comment by tuzeao** [comment]
Thanks for reply. After reading the source code with the general workflow in README.md I have some clues now.
