### ISSUE TITLE
Offline/reward-labelled dataset support?

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [lvwerra/trl#189]
Just wondering if `trl` has support for offline learning? Was hoping to use `trl` since if I'm not mistaken, compatability with `peft` is being worked on, but I was also hoping to train offline.

**Comment by lvwerra** [comment]
Not sure I fully understand the question :) Indeed, PEFT is being worked on in #145. In terms of RL algorithms only PPO is implemented at this point.

**Comment by ryan-caesar-ramos** [comment]
> In terms of RL algorithms only PPO is implemented at this point.

Thank you! This answers my question, I was wondering it `trl` had an implementation of ILQL.
