### ISSUE TITLE
About the calculated returns for value loss

### ISSUE THREAD

**Issue by yanghoonkim** [lvwerra/trl#19]
How can I understand `returns = advantages + values` in https://github.com/lvwerra/trl/blob/750f5fd5329bb81c79b00243c4c8923ac14981d5/trl/ppo.py#L219

In the original A3C paper, the loss for policy and the value function is calculated as follows (As I know, PPO shares the same mechanism):
![image](https://user-images.githubusercontent.com/9985986/122526774-9f662080-d055-11eb-8394-a22169a829d5.png)

(as I think) which means that the loss of value function should just minimize the advantage function in this code.

Would you please help me understand it? @lvwerra

**Comment by lvwerra** [comment]
As you can see later in the code the advantages are used for the loss calculations and not the returns:

https://github.com/lvwerra/trl/blob/750f5fd5329bb81c79b00243c4c8923ac14981d5/trl/ppo.py#L240
