### ISSUE TITLE
Why is the Reward Model not updated of the ppo_trainer ?

### ISSUE THREAD

**Issue by weberxie** [lvwerra/trl#194]

**Comment by lvwerra** [comment]
The reward model has to be trained before the RL/PPO loop. That's why it's not part of the trainer. However, there is a script to train a reward model in examples: https://github.com/lvwerra/trl/blob/main/examples/summarization/scripts/reward_summarization.py

Hope this helps.

**Comment by weberxie** [comment]
Thanks for your reply!

So the Reward Model will not be updated in the PPO train loop, Is this the standard process of the PPO algorithm?

Thanks.

**Comment by lvwerra** [comment]
The reward model is not part of the PPO definition. PPO assumes an environment that emits a reward based on actions. In RLHF we simulate the human preference with a reward model. In theory it could be updated from time to time to better reflect human preferences with new prompts from the model, but in many instances it is a static model. As noted before, this is not part of the PPO formulation and you can also use a simple rule for the rewards (how many times was the string "the" in the generated text).

**Comment by akk-123** [comment]
I have a question about value_head and reward model, we train value_head wish it can predict 'return' close to Reward model, why not use reward model directly, maybe not need value head?
