### ISSUE TITLE
For small models, actor, critic, init-actor, and reward can be loaded on a single machine. However, how to build the PPO process for LLM?

### ISSUE THREAD

**Issue by zhangyipin** [lvwerra/trl#196]
For small models, actor, critic, init-actor, and reward can be loaded on a single machine. However, how to build the PPO process for LLM?

**Comment by lvwerra** [comment]
TRL uses `accelerate` as its backend and as such support multi-GPU training but via data parallelism. That means the model still needs to be loaded on a single machine. In parallel we are working on a PEFT integration #145 which would allow to train much larger models on a single machine.

**Comment by zhangyipin** [comment]
Is using an HTTP server to link different modules common for larger devices like the 175B GPT? Or are there other options for how to set up each module?

**Comment by zhangyipin** [comment]
> TRL uses `accelerate` as its backend and as such support multi-GPU training but via data parallelism. That means the model still needs to be loaded on a single machine. In parallel we are working on a PEFT integration #145 which would allow to train much larger models on a single machine.

Is using an HTTP server to link different modules common for larger devices like the 175B GPT? Or are there other options for how to set up each module?

**Comment by lvwerra** [comment]
You mean having different models just as an endpoint you can ping from the main loop? I think this would be another valid option.
