### ISSUE TITLE
why compute_rewards use reward[last_non_masked_index] += score

### ISSUE THREAD

**Issue by akk-123** [lvwerra/trl#200]
In [compute_rewards function ](https://github.com/lvwerra/trl/blob/76fd085c255f7a762e36a71846af48bfd5ffd0c3/trl/trainer/ppo_trainer.py#L696)
score is the reward from RM model, why just use this as reward, in below code, reward = score + kl of last_non_masked_index，I can't understand it
```python
kl = logprob - ref_logprob
non_score_reward = -self.kl_ctl.value * kl
non_score_rewards.append(non_score_reward)
reward = non_score_reward.clone()
last_non_masked_index = mask.nonzero()[-1]
reward[last_non_masked_index] += score
rewards.append(reward)
```

**Comment by lvwerra** [comment]
The KL divergence is used as a penalty per token whereas the score is only given to the sequence as a whole thus it is received at the last generated token. The PPO loop will discount it in addition so also previous tokens benefit from it.
