### ISSUE TITLE
Blog post links broken

### ISSUE THREAD

**Issue by TeamDman** [lvwerra/trl#211]
https://huggingface.co/blog/trl-peft

![image](https://user-images.githubusercontent.com/9356891/224523236-fceddd90-a80e-4911-93ef-b4a2fdea69a4.png)

![image](https://user-images.githubusercontent.com/9356891/224523244-7e69937d-92b8-4324-9216-d7c11c4348ba.png)

Probably meant to point to the files in here

https://github.com/lvwerra/trl/tree/main/examples/sentiment/scripts/gpt-neox-20b_peft

**Comment by younesbelkada** [comment]
Hello @TeamDman 
Thanks a lot for the report! They should be now fixed with https://github.com/huggingface/blog/pull/927
Thanks!
