### ISSUE TITLE
TypeError: new(): invalid data type 'numpy.str_'

### ISSUE THREAD

**Issue by widyaputeriaulia10** [lvwerra/trl#217]
Dear Author,

I got an error while train, i tried to track which component that makes it happend, there is a problem with the loop part. I am newby in reinforcement learning, i need some advices, thank you in advance.

**Comment by lvwerra** [comment]
Could this be related to this? https://github.com/lvwerra/trl/issues/183#issuecomment-1451250635

Without code and the full error message it's a bit hard to know what's going on.

**Comment by widyaputeriaulia10** [comment]
oh thank you, the problem solved. 

I just wondering, is it possible if i use the updated GPT version such as GPT 4 ?

**Comment by lvwerra** [comment]
OpenAI will only give access to an API to use the model, not the actual weights and code to fine-tune it yourself. So no, it won't be possible to fine-tune GPT-4 which is the same situation as with GPT-3.

**Comment by widyaputeriaulia10** [comment]
Ok, I see. Thank you

Pada tanggal Rab, 15 Mar 2023 16.12, Leandro von Werra <
***@***.***> menulis:

**Comment by ShiJiawenwen** [comment]
hi, can you tell me how to solve this problem? I face the same problem.

**Comment by widyaputeriaulia10** [comment]
based on the comment  #183 (comment)
<https://github.com/lvwerra/trl/issues/183#issuecomment-1451250635>, i just
follow the instruction and it works for my case.

Good Luck

Pada tanggal Kam, 30 Mar 2023 pukul 15.23 ShiJiawenwen <
***@***.***> menulis:

**Comment by ShiJiawenwen** [comment]
Thank you！
