### ISSUE TITLE
RuntimeError: Size does not match at dimension 1 expected index [1, 14, 1] to be smaller than self [1, 0, 42024] apart from dimension 2

### ISSUE THREAD

**Issue by sammichenVV** [lvwerra/trl#230]
hello! I ran my seq2seq model using the python script in the example, but encountered this error. I only modified the code in the load model and load datasets sections.". How to solve this problem?
![image](https://user-images.githubusercontent.com/22388079/226228344-3a3ebb1d-962d-42cf-b65c-d830c29b6e3d.png).
my code:
from datasets import load_dataset
from tqdm import tqdm
from transformers import AutoTokenizer, pipeline

from trl import create_reference_model, PPOConfig, PPOTrainer, set_seed, AutoModelForSeq2SeqLMWithValueHead
from trl.core import LengthSampler
from comet import download_model, load_from_checkpoint
import yaml
import torch

def get_config():
    with open("./config.yaml") as f:
        cfg = yaml.safe_load(f)
    return cfg

param = get_config()
srclang = param['src_lang']
tgtlang = param['tgt_lang']
model_name = param['model']
reward_model = param['reward_model']
path = param['data_path']
is_ref = param['is_ref']
tqdm.pandas()

config = PPOConfig(
    model_name=model_name,
    learning_rate=1.41e-5,
)

sent_kwargs = {
    "return_all_scores": True,
    "function_to_apply": "none",
    "batch_size": 16
}

import pandas as pd

tokenizer = AutoTokenizer.from_pretrained(config.model_name)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(config.model_name)
ref_model = create_reference_model(model)

model_path = download_model(reward_model)
reward_model = load_from_checkpoint(model_path)

def read_data(file_path):
    pd_data = pd.read_csv(file_path,
                          sep="\t",
                          names=["data"],
                          header=None,
                          lineterminator='\n')
    data = list(pd_data["data"])
    data = [str(line).rstrip("\n") for line in data]

    return data

class CustomerDataset(torch.utils.data.Dataset):

    def __init__(self, file_path, srclang, tgtlang):
        self.src_data = []
        self.tgt_data = []
        self.ref_data = []
        path_src = f"{file_path}.{srclang}.src"
        path_mt = f"{file_path}.{tgtlang}.mt"
        if is_ref:
            path_ref = f"{file_path}.{tgtlang}.ref"
            self.src_data, self.tgt_data, self.ref_data = read_data(
                path_src), read_data(path_mt), read_data(path_ref)
        else:
            self.src_data, self.tgt_data = read_data(path_src), read_data(
                path_mt)

    def __getitem__(self, index):

        inputs = tokenizer.encode(self.src_data[index],
                                  return_tensors="pt").squeeze()
        query = self.src_data[index]
        if is_ref:
            input = dict(input_ids=inputs,
                         query=query,
                         ref=self.ref_data[index])
        else:
            input = dict(input_ids=inputs, query=query)

        return input

    def __len__(self):
        return len(self.src_data)

dataset = CustomerDataset(path, srclang, tgtlang)

def collator(data):
    return dict((key, [d[key] for d in data]) for key in data[0])

set_seed(config.seed)

tokenizer = AutoTokenizer.from_pretrained(config.model_name)

ppo_trainer = PPOTrainer(config,
                         model,
                         ref_model,
                         tokenizer,
                         dataset=dataset,
                         data_collator=collator)

device = ppo_trainer.accelerator.device
if ppo_trainer.accelerator.num_processes == 1:
    device = 0 if torch.cuda.is_available(
    ) else "cpu"  # to avoid a `pipeline` bug

generation_kwargs = {
    "min_length": -1,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.eos_token_id,
}
output_min_length = 4
output_max_length = 16
output_length_sampler = LengthSampler(output_min_length, output_max_length)

for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
    query_tensors = batch["input_ids"]
    response_tensors = []
    for query in query_tensors:
        gen_len = output_length_sampler()
        generation_kwargs["max_new_tokens"] = gen_len
        response = ppo_trainer.generate(query, **generation_kwargs)
        response_tensors.append(response.squeeze()[-gen_len:])
    batch["response"] = [
        tokenizer.decode(r.squeeze()) for r in response_tensors
    ]

    if is_ref:
        data = [{
            "src": src,
            "mt": mt,
            "ref": ref
        } for src, mt, ref in zip(batch["query"], batch["response"],
                                  batch["ref"])]

    else:
        data = [{
            "src": src,
            "mt": mt
        } for src, mt in zip(batch["query"], batch["response"])]

    model_output = reward_model.predict(data, batch_size=8, gpus=1)
    rewards = [torch.tensor(output) for output in model_output['scores']]

    stats = ppo_trainer.step(query_tensors, response_tensors, rewards)
    ppo_trainer.log_stats(stats, batch, rewards)

**Comment by lvwerra** [comment]
Can you run the `[T5 example](https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/t5-sentiment.py)` with your model? In addition it would be useful to see the full stack trace and the versions you are using.

**Comment by sammichenVV** [comment]
> Can you run the [T5 example](https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/t5-sentiment.py) with your model? In addition it would be useful to see the full stack trace and the versions you are using.

hi，I run the T5 example of  "facebook/wmt19-en-de",also encountered this error
![image](https://user-images.githubusercontent.com/22388079/226793757-19626ca8-aec2-4ec3-ab7a-686d5880b88e.png)
![image](https://user-images.githubusercontent.com/22388079/226793816-1bab11d9-753c-422a-b07b-ca7327fd2243.png)

**Comment by younesbelkada** [comment]
Hello @sammichenVV 
Indeed I managed to reproduce the issue, there is a known bug in all `FSMT` models that shifts the `decoder_input_ids` if `use_cache` is set to `True` (by default). Instead of computing the logits for every token in `decoder_input_ids`, the model computes the logits for the last token only, which makes its behavior inconsistent across other seq2seq models in `transformers`.
The fix is to manually force `use_cache` to be `False` before starting your PPO loop. 

Adding these lines after creating the `ref_model` and `model` solved the issue for me:

```python
model.pretrained_model.config.use_cache = False
ref_model.pretrained_model.config.use_cache = False
```

Related: https://github.com/huggingface/transformers/issues/21719

**Comment by sammichenVV** [comment]
> thanks，I solved it
