### ISSUE TITLE
get runtime error - in ppo_trainer.py -RuntimeError: Please look up dimensions by name, got: name = None.

### ISSUE THREAD

**Issue by amarazad** [lvwerra/trl#240]
when i run the  sentiment.py from examples, i get the following error at, 
```
.../python3.9/site-packages/trl/trainer/ppo_trainer.py", line 681, in train_minibatch
    loss_p, loss_v, train_stats = self.loss(old_logprobs, values, rewards, logits, vpreds, logprobs, mask) 
```
and the specific error is 

```
.../python3.9/site-packages/trl/core.py", line 109, in masked_mean
    return (values * mask).sum(axis=axis) / mask.sum(axis=axis)
RuntimeError: Please look up dimensions by name, got: name = None.

```

I have used python3.9 and installed through pip install trl . 
How to fix this?

**Comment by amarazad** [comment]
@lvwerra Do you suggest any thing to resolve this issue ?

**Comment by younesbelkada** [comment]
hi @amarazad 
You need to either update`trl`, or your `torch` version!
Let us know if you still face the issue
```bash
pip install --upgrade trl torch
```

**Comment by amarazad** [comment]
Thanks @lvwerra . By using new version of `trl`, its working now.
