### ISSUE TITLE
why not use bacth for model generate

### ISSUE THREAD

**Issue by akk-123** [lvwerra/trl#246]
In [gpt2 example code](https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt2-sentiment.py#L177)，model generate text single by single，it make traing slow，why not use batch generate?

**Comment by lvwerra** [comment]
This is addressed in #228! We need to update the examples though!

**Comment by younesbelkada** [comment]
Now the scripts are much faster thanks to @GauravVirmani 's contribution in #249!
