### ISSUE TITLE
expected scalar type Half but found Float

### ISSUE THREAD

**Issue by akk-123** [lvwerra/trl#247]
I get the same error with #219  when I run gpt2-sentiment_peft.py, in this [code](https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt2-sentiment_peft.py#L151), alreay use layer_norm_names=[], but still get this error

**Comment by lvwerra** [comment]
Let's discuss on the original issue (reopened i) so we don't have duplicate issues.
