### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'peft_config'

### ISSUE THREAD

**Issue by LZY-the-boys** [lvwerra/trl#251]
When I run the `gpt2_sentiment-peft.py` in the `examples/scripts/sentiment` dir, I run into this error:
```bash
  File "/home/xx/miniconda3/envs/trl/lib/python3.7/site-packages/trl/models/modeling_base.py", line 133, in from_pretrained
    pretrained_model_name_or_path, *model_args, **pretrained_kwargs
  File "/home/xx/miniconda3/envs/trl/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 472, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/home/xx/miniconda3/envs/trl/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2493, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'peft_config'
``` 
My trl package version is 0.4.1, transformers and peft all the newest

**Comment by Kororinpas** [comment]
I also me the same error. When I use
model = get_peft_model(model, peft_config)
to solve this problem, I also run into error.
ValueError: model must be a PreTrainedModelWrapper, got <class 'peft.peft_model.PeftModelForCausalLM'> - supported 
architectures are: (<class 'trl.models.modeling_value_head.AutoModelForCausalLMWithValueHead'>, <class 
'trl.models.modeling_value_head.AutoModelForSeq2SeqLMWithValueHead'>)

**Comment by younesbelkada** [comment]
Hi there!
This feature is new, so you need to install `trl` from source, can you try:
```bash
pip install git+https://github.com/lvwerra/trl.git
```

**Comment by lvwerra** [comment]
Closing for now, feel free to re-open if the issue persists!

**Comment by beyondguo** [comment]
I encounter a similar problem.

I have installed `trl` from source (Version: 0.4.7.dev0).

My situation is I want to train a PeftModel using the PPOTrainer:

```python
base_model_for_PPO = AutoModelForCausalLMWithValueHead.from_pretrained(
    script_args.base_model_name,
    trust_remote_code=True,
    torch_dtype=torch.bfloat16, device_map='auto'
)

ppo_model = PeftModel.from_pretrained(
    base_model_for_PPO, script_args.sft_model_lora_path
)

for name, param in ppo_model.named_parameters():
    if 'lora' in name:
        param.requires_grad = True

ppo_trainer = PPOTrainer(
    config,
    ppo_model, # model with value head
    ref_model=None,
    tokenizer=tokenizer,
    dataset=dataset,
    data_collator=collator,
    optimizer=optimizer,
)
```

Then an error shows:
`ValueError: model must be a PreTrainedModelWrapper, got <class 'peft.peft_model.PeftModelForCausalLM'> - supported architectures are: (<class 'trl.models.modeling_value_head.AutoModelForCausalLMWithValueHead'>, <class 'trl.models.modeling_value_head.AutoModelForSeq2SeqLMWithValueHead'>)`


Why I want to train a PeftModel? That is because I don't want to merge the SFT lora weights into the base model. Instead,  I want to continue training the lora layers. Is there any way I can do so? Thanks!

**Comment by younesbelkada** [comment]
Hi @beyondguo 
Thanks for bringing up the issue! 
The way to train a PEFT model using PPO is to pass the PEFT config to the PPOTrainer, in your case you can load the peft config by doing `PeftConfig.from_pretrained(xxx)` and pass that config to the trainer. Let us know if this works

**Comment by beyondguo** [comment]
Hi @younesbelkada , thanks for your reply!

Yes, as you mentioned I can pass a peft_config to PPOTrainer like:
```python
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

ppo_model = AutoModelForCausalLMWithValueHead.from_pretrained(
    config.model_name,
    load_in_8bit=False,
    device_map="auto",
    peft_config=lora_config
)
```

But what I want to do is to load a pre-trained LoRA module, instead of initializing a new LoRA module. How can I do that?

**Comment by beyondguo** [comment]
Hi @younesbelkada Thanks for your reply!

Say my lora checkpoint is `my_lora_ckp`,
Then I use the following scripts:
```python

my_peft_config = PeftConfig.from_pretrained(my_lora_ckp)

ppo_model = AutoModelForCausalLMWithValueHead.from_pretrained(
    config.model_name,
    device_map="auto",
    peft_config=my_peft_config,
)

ppo_trainer = PPOTrainer(
    config,
    ppo_model, # model with value head
    ref_model=None,
    tokenizer=tokenizer,
    dataset=dataset,
    data_collator=collator,
    optimizer=optimizer,
)
```

Will it load my **pre-trained** `my_lora_ckp` to the Base model? Or it only initializing a new LoRA?

**Comment by younesbelkada** [comment]
This will initialize new lora, if you want to initialize from that checkpoint, you need to load the fine tuned lora model outside the PPOTrainer and pass that model to `AutoModelForCausalLMWithValueHead`

**Comment by younesbelkada** [comment]
So roughly:

```python
transformers_model = AutoModelForCausalLM.from_pretrained(xxx)

peft_model = PeftModel.from_pretrained(transformers_model, my_lora_ckp)

ppo_model = AutoModelForCausalLMWithValueHead.from_pretrained(
    peft_model,
    device_map="auto",
    peft_config=my_peft_config,
)

ppo_trainer = PPOTrainer(
    config,
    ppo_model, # model with value head
    ref_model=None,
    tokenizer=tokenizer,
    dataset=dataset,
    data_collator=collator,
    optimizer=optimizer,
)
```

**Comment by beyondguo** [comment]
> So roughly:
> 
> ```python
> transformers_model = AutoModelForCausalLM.from_pretrained(xxx)
> 
> peft_model = PeftModel.from_pretrained(transformers_model, my_lora_ckp)
> 
> ppo_model = AutoModelForCausalLMWithValueHead.from_pretrained(
>     peft_model,
>     device_map="auto",
>     peft_config=my_peft_config,
> )
> 
> ppo_trainer = PPOTrainer(
>     config,
>     ppo_model, # model with value head
>     ref_model=None,
>     tokenizer=tokenizer,
>     dataset=dataset,
>     data_collator=collator,
>     optimizer=optimizer,
> )
> ```

Thanks, @younesbelkada 
It works!
Before put the model into the PPOTrainer, I also add:
```
for name, param in ppo_model.named_parameters():
    if 'lora' in name:
        param.requires_grad = True
```
make the lora modules trainable.

**Comment by younesbelkada** [comment]
Awesome ! in that case you can add a flag to make it work like that:

```python
peft_model = PeftModel.from_pretrained(transformers_model, my_lora_ckp, is_trainable=True)
```
