### ISSUE TITLE
any example for TPU?

### ISSUE THREAD

**Issue by leejason** [lvwerra/trl#252]
Is there any example running on TPU? Thank you for any advice.

**Comment by younesbelkada** [comment]
Hi @leejason 
We currently do not have an example that runs on TPU, I believe that we need to add a JAX implementation to maximize the efficiency of the TPU example, which is less likely to be supported at the moment I think

**Comment by lvwerra** [comment]
In principle, the pytorch code should run on TPUs with accelerate which is `trl`s backend: https://huggingface.co/docs/accelerate/concept_guides/training_tpu

Closing this for now, feel free to re-open if you have any questions.
