### ISSUE TITLE
[Bug] when using accelerator + deepspeed, AcceleratorState class instantiated twice with different config

### ISSUE THREAD

**Issue by Sanster** [lvwerra/trl#259]
When run `accelerate launch` (with deepspeed), the following errors will appear:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/3998421/228439528-a81196e7-68f0-404c-8ddd-cf7791d0882e.png">

I don't know why this error occurred. It was working fine without using deepspeed. Two places of initialization:

- The second initialization occurs during `AutoModelForCausalLMWithValueHead.from_pretrained(pretrained_model)`: https://github.com/lvwerra/trl/blob/237eb9c6a5b1f90f6ccb674269bd7a33533e4bf7/trl/models/modeling_base.py#L256
- The second initialization occurs during `PPOTrainer()`: https://github.com/lvwerra/trl/blob/237eb9c6a5b1f90f6ccb674269bd7a33533e4bf7/trl/trainer/ppo_trainer.py#L181

Current workaround: reset AcceleratorState after from_pretrained
```python
    model = AutoModelForCausalLMWithValueHead.from_pretrained(pretrained_model)
    AcceleratorState._reset_state()
```

**Comment by Sanster** [comment]
After make `accelerate launch` work, If it is fp16 training, you also need to modify the mini_batch_dict in `step()`, because datasets do not support fp16 and will report the following error:

<img width="766" alt="截屏2023-03-29 14 16 07" src="https://user-images.githubusercontent.com/3998421/228444410-58bf705e-fee6-4582-8d9c-2ad4d53620b1.png">

Current workaround:
https://github.com/lvwerra/trl/blob/237eb9c6a5b1f90f6ccb674269bd7a33533e4bf7/trl/trainer/ppo_trainer.py#L595

```python
mini_batch_dict = {
            "queries": queries,
            "responses": responses,
            "logprobs": all_logprobs.to(torch.float32),
            "values": values.to(torch.float32),
            "rewards": rewards,
            "masks": masks,
        }
```

**Comment by younesbelkada** [comment]
Hello @Sanster 
Thanks so much for detailing the issue, I managed to reproduce and fix the second issue, however I did not managed to reproduce the first issue, what is the DS stage you are using?
I am using DS stage 2 + mutli GPU and fp16

**Comment by younesbelkada** [comment]
Made #260 that should close the second issue, will continue to investigate for the first issue

**Comment by younesbelkada** [comment]
What is the `accelerate` version you are using?

**Comment by Sanster** [comment]
- Python: 3.8.10
- GPU: 3090
- accelerate: 0.16.0
- deepspeed: 0.8.1
- transformers: 4.26.1
- datasets: 2.10.1

**Comment by younesbelkada** [comment]
can you try with the latest `accelerate` version?
```bash
pip install --upgrade accelerate
```

**Comment by Sanster** [comment]
It works! Thanks
