### ISSUE TITLE
Question about logic about logprobs_of_labels

### ISSUE THREAD

**Issue by Bo396543018** [lvwerra/trl#265]
Hi, I am trying to integrate other models into TRL. However, due to the differences in the tokenizers, the generated input IDs are not exactly the same, and I am worried that the results may not be accurate. I am not very clear about the details here, so I would like to confirm the specific meaning of the indices used here to align the required results. I hope you can provide me with some explanations. Thank you.

**Comment by younesbelkada** [comment]
Hey @Bo396543018 
Thanks for your interest! Could you describe with more details what are the models + tokenizers you want to use?
