### ISSUE TITLE
AttributeError: 'AutoModelForCausalLMWithValueHead' object has no attribute 'get_parameter'

### ISSUE THREAD

**Issue by zi0wu** [lvwerra/trl#267]
run example.py get this error and python==3.8.15 transformers==4.20.1

**Comment by younesbelkada** [comment]
hey @zi0wu 
Can you share with us the script you are using?
Also, anything blocking on your side to not use `transformers>=4.26` ?

**Comment by zi0wu** [comment]
I solved this problem with the latest transformer. Thanks

**Comment by younesbelkada** [comment]
Thanks a lot!
