### ISSUE TITLE
how to set multi gpu?

### ISSUE THREAD

**Issue by kakaxisisan** [lvwerra/trl#272]
基于https://github.com/lvwerra/trl/blob/main/examples/toxicity/scripts/gpt-j-6b-toxicity.py 这份代码，怎么设置多GPU并行？

**Comment by younesbelkada** [comment]
Hi @kakaxisisan 
For that you would just need to add `device_map="auto"` when calling `from_pretrained`: https://github.com/lvwerra/trl/blob/a2749d9e0c96198486b788875eda3b325f76a5c8/examples/toxicity/scripts/gpt-j-6b-toxicity.py#L152 - or you can also add a custom `device_map` to define which module goes to which GPU
Let me know if that works

**Comment by lvwerra** [comment]
If you want to run the script on multiple GPUs first configure `accelerate` with:
```bash
accelerate config
```
There you can specify how many GPUs to use and what the hardware setup is.

Then you can launch training with:
```bash
accelerate launch gpt-j-6b-toxicity.py
```

Hope this helps!

**Comment by lvwerra** [comment]
Closing this for now. Feel free to re-open if there is still a question.
