### ISSUE TITLE
Questions about llama examples.

### ISSUE THREAD

**Issue by DespairL** [lvwerra/trl#282]
when I write code as examples, I got the error : 

TypeError: LlamaForCausalLM.__init__() got an unexpected keyword argument 'peft_config'

TypeError: LlamaForCausalLM.__init__() got an unexpected keyword argument 'layer_norm_names'

why can the example directly load lora config with AutoModelForCausalLMWithValueHead?

**Comment by fraferra** [comment]
@DespairL Hi, I am experiencing the same issue, could you please share how you solved this? Thank you!
