### ISSUE TITLE
Bug in the `PPOTrainer.log_stats` code

### ISSUE THREAD

**Issue by JulesGM** [lvwerra/trl#296]
https://github.com/lvwerra/trl/blob/main/trl/trainer/ppo_trainer.py#L1144

How can `torch.distributed.all_reduce` work if it's inside of a `self.accelerator.is_main_process` if block?

You should be using `self.accelerate.gather_for_metrics` anyways btw.

Have you folks tried/tested the distributed code recently at all?

**Comment by JulesGM** [comment]
nvm my bad ahah.

Still, gather_for_metrics would be interesting.

**Comment by lvwerra** [comment]
Yes, we might switch to that at some point. Since there doesn't seem to be a problem I am closing the issue for now.
