### ISSUE TITLE
clm_finetune_peft_imdb.py  need 40GB?

### ISSUE THREAD

**Issue by vpegasus** [lvwerra/trl#300]
When  reading this excellent blog: [Fine-tuning 20B LLMs with RLHF on a 24GB consumer GPU](https://huggingface.co/blog/trl-peft),  I tried the `clm_finetune_peft_imdb.py`  scripts. 
However, this script consumed over 40G GPU memory, which is  larger than that announced in the blog. 

What's wrong with it?
PS:
1. I almost modified nothing, but I followed #219 to make the code run  normally. 
2.  I use  `model_id = "EleutherAI/gpt-neox-20b"`
<img width="734" alt="截屏2023-04-12上午11 49 43" src="https://user-images.githubusercontent.com/22723154/231344489-bd38b208-71cc-4b11-a7fa-0c2146e35726.png">

After 181 steps， OOM:
```
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[11], line 1
----> 1 trainer.train()

File /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/trainer.py:1633, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1628     self.model_wrapped = self.model
   1630 inner_training_loop = find_executable_batch_size(
   1631     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1632 )
-> 1633 return inner_training_loop(
   1634     args=args,
   1635     resume_from_checkpoint=resume_from_checkpoint,
   1636     trial=trial,
   1637     ignore_keys_for_eval=ignore_keys_for_eval,
   1638 )

File /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/trainer.py:1902, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1900         tr_loss_step = self.training_step(model, inputs)
   1901 else:
-> 1902     tr_loss_step = self.training_step(model, inputs)
   1904 if (
   1905     args.logging_nan_inf_filter
   1906     and not is_torch_tpu_available()
   1907     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1908 ):
   1909     # if loss is nan or inf simply add the average of previous logged losses
   1910     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/trainer.py:2663, in Trainer.training_step(self, model, inputs)
   2661     loss = self.deepspeed.backward(loss)
   2662 else:
-> 2663     loss.backward()
   2665 return loss.detach()

File /opt/conda/envs/trl/lib/python3.10/site-packages/torch/_tensor.py:487, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File /opt/conda/envs/trl/lib/python3.10/site-packages/torch/autograd/__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

File /opt/conda/envs/trl/lib/python3.10/site-packages/torch/autograd/function.py:274, in BackwardCFunction.apply(self, *args)
    270     raise RuntimeError("Implementing both 'backward' and 'vjp' for a custom "
    271                        "Function is not allowed. You should only implement one "
    272                        "of them.")
    273 user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn
--> 274 return user_fn(self, *args)

File /opt/conda/envs/trl/lib/python3.10/site-packages/torch/utils/checkpoint.py:157, in CheckpointFunction.backward(ctx, *args)
    153 if len(outputs_with_grad) == 0:
    154     raise RuntimeError(
    155         "none of output has requires_grad=True,"
    156         " this checkpoint() is not necessary")
--> 157 torch.autograd.backward(outputs_with_grad, args_with_grad)
    158 grads = tuple(inp.grad if isinstance(inp, torch.Tensor) else None
    159               for inp in detached_inputs)
    161 return (None, None) + grads

File /opt/conda/envs/trl/lib/python3.10/site-packages/torch/autograd/__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 39.41 GiB total capacity; 31.71 GiB already allocated; 1.45 GiB free; 36.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


```

**Comment by lvwerra** [comment]
Maybe @edbeeching has some insights here. Are you running that script without any changes? What arguments are you passing?

**Comment by edbeeching** [comment]
Hi @vpegasus. The full training run was undertaken on a 80GB GPU, but it is possible to train on a lower memory GPU, you need to lower the batch size and increase the gradient accumulation steps. I think by default the `per_device_train_batch_size=8` and the `gradient_accumulation_steps=1` , you could try 1 and 8 respectively and see how much memory you have left.

If not, there are some other tricks. Let us know how you get on.

**Comment by vpegasus** [comment]
> Hi @vpegasus. The full training run was undertaken on a 80GB GPU, but it is possible to train on a lower memory GPU, you need to lower the batch size and increase the gradient accumulation steps. I think by default the `per_device_train_batch_size=8` and the `gradient_accumulation_steps=1` , you could try 1 and 8 respectively and see how much memory you have left.
> 
> If not, there are some other tricks. Let us know how you get on.

Hi, @lvwerra @edbeeching   thanks for your kindly reply.

@edbeeching  I followed your advice, to set `per_device_train_batch_size =1` and  `gradient_accumulation_steps=8`. Yes, the GPU memory cost went down (to about 24.7 G):
<img width="723" alt="截屏2023-04-13上午9 50 18" src="https://user-images.githubusercontent.com/22723154/231625890-9065fe3a-3bc8-42f8-b765-ffc95e7c84df.png">

Are there some other tricks to cost less GPU memory?  Could you please to share with me and people want to learn? thanks!

**Comment by vpegasus** [comment]
> > Hi @vpegasus. The full training run was undertaken on a 80GB GPU, but it is possible to train on a lower memory GPU, you need to lower the batch size and increase the gradient accumulation steps. I think by default the `per_device_train_batch_size=8` and the `gradient_accumulation_steps=1` , you could try 1 and 8 respectively and see how much memory you have left.
> > If not, there are some other tricks. Let us know how you get on.
> 
> Hi, @lvwerra @edbeeching thanks for your kindly reply.
> 
> @edbeeching I followed your advice, to set `per_device_train_batch_size =1` and `gradient_accumulation_steps=8`. Yes, the GPU memory cost went down (to about 24.7 G): <img alt="截屏2023-04-13上午9 50 18" width="723" src="https://user-images.githubusercontent.com/22723154/231625890-9065fe3a-3bc8-42f8-b765-ffc95e7c84df.png">
> 
> Are there some other tricks to cost less GPU memory? Could you please to share with me and people want to learn? thanks!

After 300 steps, memory cost increased:
<img width="720" alt="截屏2023-04-13上午10 17 59" src="https://user-images.githubusercontent.com/22723154/231630182-0fe17450-d4ab-4758-bd7a-b13f4170bc8d.png">

**Comment by vpegasus** [comment]
> > > Hi @vpegasus. The full training run was undertaken on a 80GB GPU, but it is possible to train on a lower memory GPU, you need to lower the batch size and increase the gradient accumulation steps. I think by default the `per_device_train_batch_size=8` and the `gradient_accumulation_steps=1` , you could try 1 and 8 respectively and see how much memory you have left.
> > > If not, there are some other tricks. Let us know how you get on.
> > 
> > 
> > Hi, @lvwerra @edbeeching thanks for your kindly reply.
> > @edbeeching I followed your advice, to set `per_device_train_batch_size =1` and `gradient_accumulation_steps=8`. Yes, the GPU memory cost went down (to about 24.7 G): <img alt="截屏2023-04-13上午9 50 18" width="723" src="https://user-images.githubusercontent.com/22723154/231625890-9065fe3a-3bc8-42f8-b765-ffc95e7c84df.png">
> > Are there some other tricks to cost less GPU memory? Could you please to share with me and people want to learn? thanks!
> 
> After 300 steps, memory cost increased: <img alt="截屏2023-04-13上午10 17 59" width="720" src="https://user-images.githubusercontent.com/22723154/231630182-0fe17450-d4ab-4758-bd7a-b13f4170bc8d.png">

Oh!, the cost is still increasing...  ( over 25GB after about 370 steps.)

<img width="722" alt="截屏2023-04-13上午10 34 47" src="https://user-images.githubusercontent.com/22723154/231632996-1186e6f3-45be-4097-94b0-49eed2fe7f44.png">

**Comment by lvwerra** [comment]
Have you tried decreasing the learning rate?

**Comment by vpegasus** [comment]
> Have you tried decreasing the learning rate?

@lvwerra  Thanks, And I decreased the learning rate  from 5e-5(default) to  1e-5 and  5e-6, however, neither made any significant change:
<img width="1158" alt="截屏2023-04-15下午2 09 47" src="https://user-images.githubusercontent.com/22723154/232195412-9bf663fa-c924-46db-839b-3c9c0a5e41a6.png">

It's too weird, could you please tell me if there is another method to turn around this situation.

**Comment by lvwerra** [comment]
Are you using the exact same dataset and script? Otherwise it's a bit hard to see what is going wrong.

**Comment by vpegasus** [comment]
> Are you using the exact same dataset and script? Otherwise it's a bit hard to see what is going wrong.

Yes, I almost made no modification, but follow #219 and add `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`(as we have 2 gpus on my machine).

Except for these, there has been no change.

Can you please rerun by using the command: `python clm_finetune_peft_imdb.py --model_name_or_path EleutherAI/gpt-neox-20b --output_dir ./ --per_device_train_batch_size=1 --gradient_accumulation_steps=8`

as I have run for several times and the loss are always going up... sad...

**Comment by edbeeching** [comment]
Hi @vpegasus , thanks again for reporting this. I was just digging through my training scripts. I think the correct 20B model was trained with the following hyperparameters:

```
python3 clm_finetune_peft_imdb.py \
 --model_name_or_path=EleutherAI/gpt-neox-20b \
 --per_device_train_batch_size=8 \
 --gradient_accumulation_steps=2 \
 --warmup_steps=50 \
 --num_train_epochs=1.0 \
 --learning_rate=5e-5 \
 --logging_steps=1 \
```
 
For your lower memory settings, you will need to lower the `per_device_train_batch_size` and raise the `gradient_accumulation_steps` to be something like 2 and 8 respectively. Let us know if that works and we will update the readme with the correct args.

**Comment by vpegasus** [comment]
> Hi @vpegasus , thanks again for reporting this. I was just digging through my training scripts. I think the correct 20B model was trained with the following hyperparameters:
> 
> ```
> python3 clm_finetune_peft_imdb.py \
>  --model_name_or_path=EleutherAI/gpt-neox-20b \
>  --per_device_train_batch_size=8 \
>  --gradient_accumulation_steps=2 \
>  --warmup_steps=50 \
>  --num_train_epochs=1.0 \
>  --learning_rate=5e-5 \
>  --logging_steps=1 \
> ```
> 
> For your lower memory settings, you will need to lower the `per_device_train_batch_size` and raise the `gradient_accumulation_steps` to be something like 2 and 8 respectively. Let us know if that works and we will update the readme with the correct args.

Hi @edbeeching  Thanks for your kindly reply.

in order to check this setting,  I used default model (`facebook/opt-125m`) with following command:
```shell
python3 clm_finetune_peft_imdb.py \
 --per_device_train_batch_size=8 \
 --gradient_accumulation_steps=2 \
 --warmup_steps=50 \
 --num_train_epochs=1.0 \
 --learning_rate=5e-5 \
 --logging_steps=1 
```
However, the loss didn't decreased significantly. 
<img width="1333" alt="截屏2023-04-19下午9 35 02" src="https://user-images.githubusercontent.com/22723154/233093652-6124b11e-6442-4b3b-9d4c-dd1564fe8164.png">


Can you help me find the reason? thanks, this problem confused me for about a week.

**Comment by vpegasus** [comment]
> > Hi @vpegasus , thanks again for reporting this. I was just digging through my training scripts. I think the correct 20B model was trained with the following hyperparameters:
> > ```
> > python3 clm_finetune_peft_imdb.py \
> >  --model_name_or_path=EleutherAI/gpt-neox-20b \
> >  --per_device_train_batch_size=8 \
> >  --gradient_accumulation_steps=2 \
> >  --warmup_steps=50 \
> >  --num_train_epochs=1.0 \
> >  --learning_rate=5e-5 \
> >  --logging_steps=1 \
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For your lower memory settings, you will need to lower the `per_device_train_batch_size` and raise the `gradient_accumulation_steps` to be something like 2 and 8 respectively. Let us know if that works and we will update the readme with the correct args.
> 
> Hi @edbeeching Thanks for your kindly reply.
> 
> in order to check this setting quickly, I used default model (`facebook/opt-125m`) with following command:
> 
> ```shell
> python3 clm_finetune_peft_imdb.py \
>  --per_device_train_batch_size=8 \
>  --gradient_accumulation_steps=2 \
>  --warmup_steps=50 \
>  --num_train_epochs=1.0 \
>  --learning_rate=5e-5 \
>  --logging_steps=1 
> ```
> 
> However, the loss didn't decrease significantly. <img alt="截屏2023-04-19下午9 35 02" width="1333" src="https://user-images.githubusercontent.com/22723154/233093652-6124b11e-6442-4b3b-9d4c-dd1564fe8164.png">
> 
> Can you help me find the reason? thanks, this problem confused me for about a week.
> 
> (PS: I will post the loss for training `EleutherAI/gpt-neox-20b` once the training process is finished, tomorrow)

Hi, @edbeeching, I just finished the training proces for  `EleutherAI/gpt-neox-20b`, However, with settings suggested, the loss still increased. So sad...

![image](https://user-images.githubusercontent.com/22723154/233217432-ff20c7ca-ee21-4bfb-b2e8-aabad299eb5d.png)

Because I am a newbee in terms of using `trl` and `peft`, so I wonder could you please offer us a completely successfully scripts with settings announced？ As we just run the first script, the reproduction process is  too cumbersome to have confidence completing the whole procedure as stated in the blog: 
[Fine-tuning 20B LLMs with RLHF on a 24GB consumer GPU
Published March 9, 2023](https://huggingface.co/blog/trl-peft)

Actually, I also would like to try the wonderful blog [StackLLaMA: A hands-on guide to train LLaMA with RLHF](https://huggingface.co/blog/stackllamahttps://huggingface.co/blog/stackllama), but stuck in here without any step forward, which makes us very frustrated.
Please help us go through this unhappy journey,  because we are anxious to experience this amazing idea of  training the large model with limited sources
Thanks very much

**Comment by vpegasus** [comment]
@wenxichen hi, did you solve this problem about training loss increasing for clm finetune?

**Comment by vpegasus** [comment]
@edbeeching  Do you still keep the wandb logs for running `clm_finetune_peft_imdb.py`,  And could you please share it for us? It may help us debugging quickly. Thanks~

**Comment by ghomasHudson** [comment]
> > > Hi @vpegasus , thanks again for reporting this. I was just digging through my training scripts. I think the correct 20B model was trained with the following hyperparameters:
> > > ```
> > > python3 clm_finetune_peft_imdb.py \
> > >  --model_name_or_path=EleutherAI/gpt-neox-20b \
> > >  --per_device_train_batch_size=8 \
> > >  --gradient_accumulation_steps=2 \
> > >  --warmup_steps=50 \
> > >  --num_train_epochs=1.0 \
> > >  --learning_rate=5e-5 \
> > >  --logging_steps=1 \
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For your lower memory settings, you will need to lower the `per_device_train_batch_size` and raise the `gradient_accumulation_steps` to be something like 2 and 8 respectively. Let us know if that works and we will update the readme with the correct args.
> > 
> > 
> > Hi @edbeeching Thanks for your kindly reply.
> > in order to check this setting quickly, I used default model (`facebook/opt-125m`) with following command:
> > ```shell
> > python3 clm_finetune_peft_imdb.py \
> >  --per_device_train_batch_size=8 \
> >  --gradient_accumulation_steps=2 \
> >  --warmup_steps=50 \
> >  --num_train_epochs=1.0 \
> >  --learning_rate=5e-5 \
> >  --logging_steps=1 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, the loss didn't decrease significantly. <img alt="截屏2023-04-19下午9 35 02" width="1333" src="https://user-images.githubusercontent.com/22723154/233093652-6124b11e-6442-4b3b-9d4c-dd1564fe8164.png">
> > Can you help me find the reason? thanks, this problem confused me for about a week.
> > (PS: I will post the loss for training `EleutherAI/gpt-neox-20b` once the training process is finished, tomorrow)
> 
> Hi, @edbeeching, I just finished the training process for `EleutherAI/gpt-neox-20b`, However, with settings suggested, the loss still increased. So sad...
> 
> ![image](https://user-images.githubusercontent.com/22723154/233217432-ff20c7ca-ee21-4bfb-b2e8-aabad299eb5d.png)
> 
> Because I am a newbee in terms of using `trl` and `peft`, so I wonder could you please offer us a completely successfully scripts with settings announced？ As we just run the first script, the reproduction process is too cumbersome to have confidence completing the whole procedure as stated in the blog: [Fine-tuning 20B LLMs with RLHF on a 24GB consumer GPU Published March 9, 2023](https://huggingface.co/blog/trl-peft)
> 
> Actually, I also would like to try the wonderful blog [StackLLaMA: A hands-on guide to train LLaMA with RLHF](https://huggingface.co/blog/stackllamahttps://huggingface.co/blog/stackllama), but stuck in here without any step forward, which makes us very frustrated. Please help us go through this unhappy journey, because we are anxious to experience this amazing idea of training the large model with limited sources Thanks very much

I'm seeing the same thing - loss staying the same with both the previously recommended and default settings.

**Comment by ZakiaSalod** [comment]
Hi there

Could you please advise where to find the gpt-neox-20b_peft/clm_finetune_peft_imdb.py script? That is mentioned in this post: https://huggingface.co/blog/trl-peft

All the 3 scripts links under the "Overview of the training scripts:" section in this post (https://huggingface.co/blog/trl-peft) are broken - it says "404 - page not found" - thanks in advance!

**Comment by vadimkantorov** [comment]
> 404 - page not found

same problem
