### ISSUE TITLE
Support for Codegen gpt2 model 

### ISSUE THREAD

**Issue by amarazad** [lvwerra/trl#301]
I tried to load the model and reference model using the following for codegen model
`model = AutoModelForCausalLM.from_pretrained(ckpt,
            trust_remote_code=True)`
where `ckpt` is salesforce finetuned model path. 
I get the following error while initializing 
`    ppo_trainer = PPOTrainer(config, model, ref_model, tokenizer, dataset=dataset, data_collator=collator)` 
`ppo_trainer = PPOTrainer(config, model, ref_model, tokenizer, dataset=dataset, data_collator=collator)
*** ValueError: model must be a PreTrainedModelWrapper, got <class 'transformers.models.codegen.modeling_codegen.CodeGenForCausalLM'> - supported architectures are: (<class 'trl.models.modeling_value_head.AutoModelForCausalLMWithValueHead'>, <class 'trl.models.modeling_value_head.AutoModelForSeq2SeqLMWithValueHead'>)`

@lvwerra   Any suggestions ?

**Comment by amarazad** [comment]
Thanks @lvwerra . It worked.

**Comment by younesbelkada** [comment]
Awesome! Closing the issue now
