### ISSUE TITLE
Question about generation_kwargs in Stack_LLama rl_training

### ISSUE THREAD

**Issue by Kororinpas** [lvwerra/trl#305]
`generation_kwargs = {
 "min_length": -1,
"top_k": 0.0,
"top_p": 1.0,
"do_sample": True,
"pad_token_id": tokenizer.pad_token_id,
"eos_token_id": 100_000,
`

I noticed that in this code snippet, unlike previous examples, min_length is not set to -1, and eos_token_id is set to a value that is not in the tokenizer. I wonder if there is special meaning of these generation settings?  Just like min_length set to -1 can avoid negative KL and eos_token_id set to -1 can avoid short generations as mentioned in #203.

**Comment by lvwerra** [comment]
There was a PR introduced in transformers where `eos_token_id` throws an error if not a positive number. Using a positive number greater than the vocab size has the same effect: This token id is never generated an thus the generation doesn't stop until `max_new_tokens` is reached.

**Comment by Kororinpas** [comment]
@lvwerra Thank you, I now understand the reason for setting generation_kwargs. However, I encountered a strange OOM error while running stack_llama RL Training. My code is basically the same as RL Training, except for two points. The first point is that I use my own trained reward model based on GPT-Neo. The second point is that I have reduced the batch_size to 1 and shortened the length sampler to (16, 24) to avoid increasing memory usage due to long sentences.

The OOM error does not occur at the beginning of the run, but rather at some point during the processing of a specific sample, where the memory usage suddenly increases. I conducted two tests using two different seeds, and the error occurred in the 4th batch during the first test and in the 56th batch during the second test. In both cases, the memory usage suddenly increased during the ppo_trainer_step step while training on the two specific samples. Here are the specific error messages, as well as the tensor and reward of the generated sample. Since my understanding of the application of PPO in RLHF is limited, would it be possible for me to ask for your advice regarding the possible reasons for this error?

 /usr/local/lib/python3.9/dist-packages/trl/trainer/ppo_trainer.py:597 in step                    │
│                                                                                                  │
│    594 │   │   model_inputs_names = list(model_inputs.keys())                                    │
│    595 │   │                                                                                     │
│    596 │   │   with torch.no_grad():                                                             │
│ ❱  597 │   │   │   all_logprobs, _, values, masks = self.batched_forward_pass(self.model, queri  │
│    598 │   │   │                                                                                 │
│    599 │   │   │   # for when the model is a peft model                                          │
│    600 │   │   │   if self.is_peft_model and hasattr(                                            │
│                                                                                                  │
│ /usr/lib/python3.9/contextlib.py:79 in inner                                                     │
│                                                                                                  │
│    76 │   │   @wraps(func)                                                                       │
│    77 │   │   def inner(*args, **kwds):                                                          │
│    78 │   │   │   with self._recreate_cm():                                                      │
│ ❱  79 │   │   │   │   return func(*args, **kwds)                                                 │
│    80 │   │   return inner                                                                       │
│    81                                                                                            │
│    82                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/trl/trainer/ppo_trainer.py:840 in batched_forward_pass    │
│                                                                                                  │
│    837 │   │   │   input_kwargs = {key: value[i * fbs : (i + 1) * fbs] for key, value in model_  │
│    838 │   │   │   query_batch = queries[i * fbs : (i + 1) * fbs]                                │
│    839 │   │   │   response_batch = responses[i * fbs : (i + 1) * fbs]                           │
│ ❱  840 │   │   │   logits, _, values = model(**input_kwargs)                                     │
│    841 │   │   │                                                                                 │
│    842 │   │   │   if self.is_encoder_decoder:                                                   │
│    843 │   │   │   │   input_ids = input_kwargs["decoder_input_ids"]                             │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1538 in _call_impl             │
│                                                                                                  │
│   1535 │   │   │   bw_hook = hooks.BackwardHook(self, full_backward_hooks, backward_pre_hooks)   │
│   1536 │   │   │   args = bw_hook.setup_input_hook(args)                                         │
│   1537 │   │                                                                                     │
│ ❱ 1538 │   │   result = forward_call(*args, **kwargs)                                            │
│   1539 │   │   if _global_forward_hooks or self._forward_hooks:                                  │
│   1540 │   │   │   for hook_id, hook in (                                                        │
│   1541 │   │   │   │   *_global_forward_hooks.items(),                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/trl/models/modeling_value_head.py:161 in forward          │
│                                                                                                  │
│   158 │   │   """                                                                                │
│   159 │   │   kwargs["output_hidden_states"] = True  # this had already been set in the LORA /   │
│   160 │   │                                                                                      │
│ ❱ 161 │   │   base_model_output = self.pretrained_model(                                         │
│   162 │   │   │   input_ids=input_ids,                                                           │
│   163 │   │   │   past_key_values=past_key_values,                                               │
│   164 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/peft/peft_model.py:530 in forward                         │
│                                                                                                  │
│   527 │   │   **kwargs,                                                                          │
│   528 │   ):                                                                                     │
│   529 │   │   if not isinstance(self.peft_config, PromptLearningConfig):                         │
│ ❱ 530 │   │   │   return self.base_model(                                                        │
│   531 │   │   │   │   input_ids=input_ids,                                                       │
│   532 │   │   │   │   attention_mask=attention_mask,                                             │
│   533 │   │   │   │   inputs_embeds=inputs_embeds,                                               │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/hooks.py:165 in new_forward                    │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py:772 in        │
│ forward                                                                                          │
│                                                                                                  │
│   769 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return   │
│   770 │   │                                                                                      │
│   771 │   │   # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)    │
│ ❱ 772 │   │   outputs = self.model(                                                              │
│   773 │   │   │   input_ids=input_ids,                                                           │
│   774 │   │   │   attention_mask=attention_mask,                                                 │
│   775 │   │   │   past_key_values=past_key_values,                                               │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/hooks.py:165 in new_forward                    │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py:621 in        │
│ forward                                                                                          │
│                                                                                                  │
│   618 │   │   │   │   │   None,                                                                  │
│   619 │   │   │   │   )                                                                          │
│   620 │   │   │   else:                                                                          │
│ ❱ 621 │   │   │   │   layer_outputs = decoder_layer(                                             │
│   622 │   │   │   │   │   hidden_states,                                                         │
│   623 │   │   │   │   │   attention_mask=attention_mask,                                         │
│   624 │   │   │   │   │   past_key_value=past_key_value,                                         │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/hooks.py:165 in new_forward                    │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py:316 in        │
│ forward                                                                                          │
│                                                                                                  │
│   313 │   │   hidden_states = self.input_layernorm(hidden_states)                                │
│   314 │   │                                                                                      │
│   315 │   │   # Self Attention                                                                   │
│ ❱ 316 │   │   hidden_states, self_attn_weights, present_key_value = self.self_attn(              │
│   317 │   │   │   hidden_states=hidden_states,                                                   │
│   318 │   │   │   past_key_value=past_key_value,                                                 │
│   319 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/accelerate/hooks.py:165 in new_forward                    │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py:253 in        │
│ forward                                                                                          │
│                                                                                                  │
│   250 │   │   │   attn_weights = torch.max(attn_weights, torch.tensor(torch.finfo(attn_weights   │
│   251 │   │                                                                                      │
│   252 │   │   # upcast attention to fp32                                                         │
│ ❱ 253 │   │   attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).   │
│   254 │   │   attn_output = torch.matmul(attn_weights, value_states)                             │
│   255 │   │                                                                                      │
│   256 │   │   if attn_output.size() != (bsz, self.num_heads, q_len, self.head_dim):              │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/functional.py:1845 in softmax                    │
│                                                                                                  │
│   1842 │   if dtype is None:                                                                     │
│   1843 │   │   ret = input.softmax(dim)                                                          │
│   1844 │   else:                                                                                 │
│ ❱ 1845 │   │   ret = input.softmax(dim, dtype=dtype)                                             │
│   1846 │   return ret                                                                            │
│   1847                                                                                           │
│   1848                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 10.74 GiB (GPU 0; 39.56 GiB total capacity; 18.20 GiB 
already allocated; 2.88 GiB free; 35.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory
try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF

56it [13:14, 14.96s/it][tensor([   13,   632,    13,    13, 29911,  8243,    13, 31886, 19398,  7437,
         4951, 21620, 24595, 19756,  8708, 28049, 28472,  3108, 19514,    13,
        11370,  7411, 18359], device='cuda:0')]
[tensor([-1.7113])]
56it [13:36, 14.58s/it]
