### ISSUE TITLE
Supporting Custom HuggingFace model in TRL

### ISSUE THREAD

**Issue by srikar2097** [lvwerra/trl#306]
Hi Leandro @lvwerra , 
Thank you for sharing this wonderful library on-top of HuggingFace. I have a question on the inheritance structure for `PPOConfig`. In the `trl` library, `PPOConfig` is merely inherited from python `object`, however in Huggingface the following structure is followed: 
`PushToHubMixin` -> `PreTrainedConfig` -> `T5Config` or `GPT2Config`

Here are my questions:
1. Is there any specific reason `PPOConfig` does not inherit from `PushToHubMixin` or `PreTrainedConfig`? 
2. I am trying to support a custom HuggingFace model (and its config) in `trl`, can you suggest any guidance on where to start (which classes or files to modify)?

**Comment by srikar2097** [comment]
Hi Leandro @lvwerra , Appreciate your response. I have a custom **model** and **config** which is based on T5. Here is what I did:

1. I created my custom class similar to `AutoModelForSeq2SeqLMWithValueHead` in `modeling_value_head.py`. My custom class is a sub-class of `PreTrainedModelWrapper` (again similar to how you did it.
1. The custom config is a subclass of `PretrainedConfig`
1. I load the weights from my custom model.

HuggingFace version: 4.29.2
TRL version: 0.4.1
Torch version: 1.13.1

I get the following issue:
```
You are using a model of type t5 to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "test.py", line 132, in <module>
    model = CustomWithValueHeadTRL.from_pretrained(config.model_name, config=custom_config,)
  File "/opt/conda/envs/lib/python3.9/site-packages/trl/models/modeling_base.py", line 133, in from_pretrained
    pretrained_model = cls.transformers_parent_class.from_pretrained(
  File "/opt/conda/envs/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 470, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'mytrl_models.CustomVisionConfig'> for this kind of AutoModel: AutoModelForSeq2SeqLM.
Model type should be one of BartConfig, BigBirdPegasusConfig, BlenderbotConfig, BlenderbotSmallConfig, EncoderDecoderConfig, FSMTConfig, GPTSanJapaneseConfig, LEDConfig, LongT5Config, M2M100Config, MarianConfig, MBartConfig, MT5Config, MvpConfig, NllbMoeConfig, PegasusConfig, PegasusXConfig, PLBartConfig, ProphetNetConfig, SwitchTransformersConfig, T5Config, XLMProphetNetConfig.
```

I would have thought subclassing my from `CustomVisionConfig` from `PretrainedConfig` would not cause Unrecognized configuration class. That does not seem to be the case. Help!

**Comment by srikar2097** [comment]
Hi @lvwerra would appreciate some help or inputs for this issue. thanks again.

**Comment by lvwerra** [comment]
It looks like you issue is more loading your custom model with a custom config with transformers. I think you should first register your custom classes, see [here](https://huggingface.co/docs/transformers/custom_models#registering-a-model-with-custom-code-to-the-auto-classes) for more info.
