### ISSUE TITLE
runtime error in sentiment.py

### ISSUE THREAD

**Issue by amarazad** [lvwerra/trl#308]
Hi @lvwerra, 
I encounter the following error while running the sentiment.py example. 

```
/anaconda3/envs/py39_rl/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
    input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs
AttributeError: 'list' object has no attribute 'unsqueeze'
```

The error is appearing at the following [line](https://github.com/lvwerra/trl/blob/160d0c9d6cdbc8b247bad4aa8f97f2c57dc4a60f/examples/sentiment/scripts/gpt2-sentiment.py#L176)
```
for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
    query_tensors = batch["input_ids"]

    # Get response from gpt2
    response_tensors = ppo_trainer.generate(
        query_tensors, return_prompt=False, length_sampler=output_length_sampler, **generation_kwargs
    )
```
I am using the latest version of trl. 
Any suggestions ?

**Comment by GauravVirmani** [comment]
What version of `trl` are you using?

Try installing the latest version from source using

    pip install -e .

**Comment by amarazad** [comment]
Thanks @lvwerra . I guess i figured that out as well. It requires 
```
transformers==4.27.4
torch=2.0.0
```
