### ISSUE TITLE
why can't I download the stack llama rm dataset from huggingface?

### ISSUE THREAD

**Issue by yzxyzh** [lvwerra/trl#310]
I've tried to download using git clone via https and git from lvwerra/stack-exchange-paired, all told me that repository not found. Any idea what is going wrong? I can download other datasets normally btw. Is this because some files are marked as unsafe?

Thanks!

**Comment by lvwerra** [comment]
Can you provide the exact command you used and what the error is?

**Comment by yzxyzh** [comment]
sure. Below is my command:

git clone git@hf.co:lvwerra/stack-exchange-paired

and this is the response:

Cloning into 'stack-exchange-paired'...
remote:
remote: ========================================================================
remote:
remote: ERROR: Repository not found

remote:
remote: ========================================================================
remote:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lvwerra** [comment]
Can you try:

```bash
git lfs install
git clone https://huggingface.co/datasets/lvwerra/stack-exchange-paired
```

**Comment by yzxyzh** [comment]
> Can you try:
> 
> ```shell
> git lfs install
> git clone https://huggingface.co/datasets/lvwerra/stack-exchange-paired
> ```

Oh it works! thank you so much!
