### ISSUE TITLE
Best Way To Include Multiple Rewards?

### ISSUE THREAD

**Issue by JosephGatto** [lvwerra/trl#314]
Suppose I wanted to have two classifiers dictate the reward signal. Whats the best way to do this outside of just adding their rewards together?

**Comment by younesbelkada** [comment]
Hi @JosephGatto 
Good question. As you suggested I would maybe first try to combine both rewards with some sort of aggregation strategy (sum, mean, weighted sum, etc)
Here I am just brainstorming, but another direction that could make sense would be to train 2 adapters trained each on a different reward classifier then combine those adapters later on. This has been proved to work really well on images recently: https://github.com/huggingface/peft/blob/main/examples/lora_dreambooth/lora_dreambooth_inference.ipynb 

![Screenshot 2023-04-25 at 11 01 50](https://user-images.githubusercontent.com/49240599/234228011-d720a886-7b13-430a-bf3f-557f5c236af6.png)

So maybe it would also work for text models
