### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by oroojlooy** [lvwerra/trl#317]
It seems that `torch.distributed.launch` is deprecated in torch 2.0 and instead of 
`python -m torch.distributed.launch --nproc_per_node=1 reward_summarization.py --bf16`
one needs to run:
`torchrun --nproc_per_node=1 reward_summarization.py --bf16`
or 
`python -m torch.distributed.run --nproc_per_node=1 reward_summarization.py --bf16`

Using `python -m torch.distributed.launch --nproc_per_node=1 reward_summarization.py --bf16` with torch 2.0 ends in
```
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=0']
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 194889) of binary: /home/ubuntu/miniconda3/envs/trl/bin/python
```

I did not know if it is OK to send a PR to update such minor error. So, wanted to let you know this so that you can update the README on the next commit.

**Comment by younesbelkada** [comment]
hi @oroojlooy 
We would indeed want to warn users on this. In my opinion this should go in the documentation page. I will add a new documentation page dedicated to `accelerate` + multi-gpu etc. I will ping you once I will open a PR for this

**Comment by younesbelkada** [comment]
Hello @oroojlooy 
I just merged #320 , would you mind opening a PR and add a note on the file `docs/customization.mdx` describing your finding? 🤗

**Comment by oroojlooy** [comment]
I just sent a PR: https://github.com/lvwerra/trl/pull/324

**Comment by younesbelkada** [comment]
Closing as #324 being closed
