### ISSUE TITLE
Problem when using seq2seq model 

### ISSUE THREAD

**Issue by eleluong** [lvwerra/trl#319]
When i use example from https://huggingface.co/docs/trl/quickstart, the problem is list of tensor (input_ids) convert to tensor of list input_ids in :
def prepare_model_inputs(self, queries: torch.Tensor, responses: torch.Tensor):
        if self.is_encoder_decoder:
            input_data = self.data_collator(
                [{"input_ids": q, "attention_mask": torch.ones_like(q)} for q in queries]
            ).to(self.current_device)
when i use queries[0], it works perfectly fine.

**Comment by younesbelkada** [comment]
Hi @eleluong 
Which example are you referring exactly? Can you share a reproducible script? 
Thanks!

**Comment by younesbelkada** [comment]
Hi @eleluong 
the script works on the main branch of `trl`:
```python
import torch
from transformers import AutoTokenizer
from trl import PPOTrainer, PPOConfig, AutoModelForSeq2SeqLMWithValueHead, create_reference_model
from trl.core import respond_to_batch
from tqdm import tqdm
from typing import List

MBART = "facebook/mbart-large-50"

model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(MBART, torch_dtype =torch.bfloat16).to(0)
model_ref = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(MBART, torch_dtype =torch.bfloat16).to(0)
tokenizer = AutoTokenizer.from_pretrained(MBART)

ppo_config = {'batch_size': 1}
config = PPOConfig(**ppo_config)
ppo_trainer = PPOTrainer(config, model, model_ref, tokenizer)

query_txt = "This morning I went to the "
query_tensor = tokenizer.encode(query_txt, return_tensors="pt").to(0)

response_tensor = respond_to_batch(model, query_tensor).to(0)
response_txt = tokenizer.decode(response_tensor[0,:])

reward = [torch.tensor(1.0).to(0)]
train_stats = ppo_trainer.step([query_tensor[0]], [response_tensor[0]], reward)
```
Can you try again with the latest main branch of `trl` ?
```bash
pip install git+https://github.com/lvwerra/trl.git
```
