### ISSUE TITLE
Env Rewards increasing but Model Output Quality going down

### ISSUE THREAD

**Issue by bhavnicksm** [lvwerra/trl#322]
Hey! 

These are the graphs when training a model on the OpenAI TLDR dataset with TRL, using a GPT2 reward model with decent accuracy

![image](https://user-images.githubusercontent.com/11348086/234563348-2e8051b2-e0be-4094-806d-b8f2628b2c0a.png)

It seems that the model is learning but the quality of the model is actually going down.

![image](https://user-images.githubusercontent.com/11348086/234563695-6dbd8e62-4298-4ee8-bcba-c34a47160990.png)

The model learnt to output a lot of Sssss for greater reward which was not happening before. 

How do I evaluate the issue in such a case?

**Comment by bhavnicksm** [comment]
Here are the PPO returns graphs for the same model

![image](https://user-images.githubusercontent.com/11348086/234564216-ea8bfecc-baf9-41e7-9554-24373060e9bc.png)

**Comment by lvwerra** [comment]
It looks like the issue could be the reward model - if the model can generate sequences that yield high rewards from the reward model it can start to generate gibberish that still gets better rewards.
