### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float in finetuning the frozen 8-bits Low Rank Adapter (cm_finetune_peft_imdb.py)

### ISSUE THREAD

**Issue by leclem** [lvwerra/trl#328]
I read the great article https://huggingface.co/blog/trl-peft and wanted to reproduce the highlighted steps

Nevertheless, when trying to run examples/sentiment/scripts/gpt-neox-20b_peft/clm_finetune_peft_imdb.py , I get the error "RuntimeError: expected scalar type Half but found Float".

Any idea what would cause this? It seems to have something to do with the int8 precision which is neither Half nor Float.

Here is a notebook reproducing the issue https://colab.research.google.com/drive/14QR0jsWVqGcJXaUXKgRXJelIHdcG3SPV?authuser=1#scrollTo=d1v0s3DxwWbU

**Comment by younesbelkada** [comment]
Hey @leclem 
Thanks for your interest and feedback, I think that you should try with the latest `main` branch of `peft`:
```bash
pip install git+https://github.com/huggingface/peft.git
```
Can you try with the updated library and let us know how it goes?

**Comment by leclem** [comment]
Thank you for your fast anwser!
Same result with the latest version of peft (I updated the notebook : https://colab.research.google.com/drive/14QR0jsWVqGcJXaUXKgRXJelIHdcG3SPV?authuser=1#scrollTo=XP1OoadswI-I )
