### ISSUE TITLE
How can I implement trl with BART model

### ISSUE THREAD

**Issue by shuishen112** [lvwerra/trl#33]
Note that the trl is only implemented with GPT2 model. Is it possible to implement with BART?

**Comment by lvwerra** [comment]
This should be in principle possible, maybe this needs some modifications to the `PPOTrainer` but you can probably treat the decoder of an encoder-decoder architecture such as BART or T5 like the GPT-2 decoder. This was also requested in #13 and #23. Feel free to open a PR if you have a working solution!
