### ISSUE TITLE
trl with sentence-transformers?

### ISSUE THREAD

**Issue by leoplusx** [lvwerra/trl#332]
Can I use trl to improve sentence-transformers on semantic search tasks?

I hear that trl is more sample efficient than normal training or fine tuning. So in theory, it should be possible to use this technique to domain adapt a sentence-transformer with far fewer annotation triplets.

I am thinking

a) using it on a pre-trained sentence-transformer directly or

b) using it on a pre-trained transformer model, and then combining that model into a sentence-transformer by adding a pooling layer.

I haven't found any documentation on this. Is there any reason why this shouldn't work? What would be the best way to go about it?

Thanks!

**Comment by younesbelkada** [comment]
Hi @leobaumgardt 
This sounds like you need to integrate `trl` with `sentence-transformers` as the `PPOTrainer` supports only the `PreTrainedModelWrapper` class. 
I would advocate to have a look at that class first: https://github.com/lvwerra/trl/blob/main/trl/models/modeling_base.py and assess what you would need to integrate the models from `sentence-transformers`.

**Comment by jn2clark** [comment]
@leobaumgardt I would be interested in this as well
