### ISSUE TITLE
【discussion】why sft‘s train dataset using packing technique？

### ISSUE THREAD

**Issue by echoht** [lvwerra/trl#346]
from https://huggingface.co/docs/trl/main/en/using_llama_models， I know the reason is “ more efficient”. But if we only has SFT stage, does the packing technique lower the capability of the fine-tuned model when comparing with the classical data loader?

**Comment by younesbelkada** [comment]
Hi @echoht 
Good question!
My understanding is that this enables the model to "see" much more data than having padded inputs. In a single batch you could fit let's say up to N * batch_size examples, whereas for the classic dataloader you would sample only a single example per example, so a total of batch_size examples.

**Comment by lvwerra** [comment]
There are two regimes here I think:
- when you have a lot of data (e.g. O(100k)) you want to train as much and as fast as possible. Packing makes a lot of sense her.
- when you have limited data (e.g. O(100-1k)) you want to make as much of the few samples as possible and don't corrupt any of them. Probably you don't want packing here.

**Comment by echoht** [comment]
> There are two regimes here I think:
> 
> * when you have a lot of data (e.g. O(100k)) you want to train as much and as fast as possible. Packing makes a lot of sense her.
> * when you have limited data (e.g. O(100-1k)) you want to make as much of the few samples as possible and don't corrupt any of them. Probably you don't want packing here.

Thank you for reply. I have no more questions.
