### ISSUE TITLE
Potential typo when calculating reference log probabilities?

### ISSUE THREAD

**Issue by rmill040** [lvwerra/trl#354]
I'm looking at the code in the `ppo_trainer.py` file and this code block:

```python
        with torch.no_grad():
            all_logprobs, _, values, masks = self.batched_forward_pass(self.model, queries, responses, model_inputs)

            # for when the model is a peft model
            if self.is_peft_model and hasattr(
                self.accelerator.unwrap_model(self.model).pretrained_model, "disable_adapter"
            ):
                with self.accelerator.unwrap_model(self.model).pretrained_model.disable_adapter():
                    ref_logprobs, _, _, _ = self.batched_forward_pass(self.model, queries, responses, model_inputs)
            elif self.is_peft_model and not hasattr(self.model.pretrained_model, "disable_adapter"):
                raise ValueError(
                    "You are using a `peft` version that does not support `disable_adapter`. Please update your `peft` version to the latest version."
                )

            else:
                ref_logprobs, _, _, _ = self.batched_forward_pass(self.ref_model, queries, responses, model_inputs)
```
If you look at the condition where the model is a peft model, the `ref_logprobs` are calculated using the `self.model` attribute. If you compare this to the else conditon, the `ref_logprobs` are calculated using the `self.ref_model` attribute. Should the first line use the `self.ref_model` instead of `self.model` to calculate the `ref_logprobs`?

Pointing to the actual lines of code:
- Line using `self.model` that may have a typo since it uses the active model: https://github.com/lvwerra/trl/blob/c85cdbdbd0d956bbc6f5a8e04b0036648480e7a1/trl/trainer/ppo_trainer.py#L606
- Line using `self.ref_model` that uses the actual reference model: https://github.com/lvwerra/trl/blob/c85cdbdbd0d956bbc6f5a8e04b0036648480e7a1/trl/trainer/ppo_trainer.py#L613

**Comment by younesbelkada** [comment]
Hi @rmill040 
Thanks for the issue, you are raising a good points that is worth clarifying,
If you analyse that snippet well, for PEFT models, we retrieve the reference logprobs inside the `model.disable_adapter()` context manager:
```
with self.accelerator.unwrap_model(self.model).pretrained_model.disable_adapter():
```
Which means that whatever operation we do inside that context manager with `self.model` will disable the adapters of the model, hence the active model will behave exactly as the reference model. 
Hope this is clear!

**Comment by rmill040** [comment]
@younesbelkada thanks for the explanation! That makes sense now 😀 

I'll go ahead and close this issue. Keep up the great work on this library!
