### ISSUE TITLE
Getting `trainer.generate()` to generate output using the reference model

### ISSUE THREAD

**Issue by philharmonikerzzy** [lvwerra/trl#357]
Often in the PPO process we need to use the relative difference of rewards from the output of the model and the reference model. Would it be possible to allow the `trainer.generate()` method to specify which of the two models we want to see output from?

**Comment by younesbelkada** [comment]
this sounds like a good idea cc @lvwerra 
However you can call generate directly with `trainer.ref_model.generate()` I think,

**Comment by philharmonikerzzy** [comment]
Sounds good. Although i think the generate() function has a bunch of extra logic before and after calling the generate() on the actual model itself. Would probably have to duplicate those code in my training script to ensure consistency.

Another thing is, i'm currently using the peft `disable_adapter()` approach for the reference model, so i think i would actually need to manually do that instead of using the ref_model field directly?
