### ISSUE TITLE
RuntimeError: 'weight' must be 2-D

### ISSUE THREAD

**Issue by yashpreets** [lvwerra/trl#361]
Using deepspeed zero3

`ref_model = create_reference_model(model)`
causes issue

`RuntimeError: 'weight' must be 2-D`

Works when creating reference model directly
`ref_model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(model_checkpoint).eval()`

**Comment by lvwerra** [comment]
Could you provide a minimal reproducible example?
