### ISSUE TITLE
ValueError: weight is on the meta device, we need a 'value' to put in on 0

### ISSUE THREAD

**Issue by xuyingjie521** [lvwerra/trl#364]
![截屏2023-05-12 16 12 10](https://github.com/lvwerra/trl/assets/26736518/bb03a6e2-ae23-4c10-8fc2-bb20b7afae8f)
![截屏2023-05-12 16 12 31](https://github.com/lvwerra/trl/assets/26736518/1a2e4467-2afa-44fd-bb1d-3ecf98b77737)

This error is always reported when loading the llama or gpt-2 training  reward_modeling.py file!
Very urgent, please find an answer ，thanks！

**Comment by younesbelkada** [comment]
hi @xuyingjie521 
Can you make sure you are using the latest versions of `transformers` and `accelerate`?
```bash
pip install --upgrade accelerate transformers
```

**Comment by xuyingjie521** [comment]
> hi @xuyingjie521 Can you make sure you are using the latest versions of `transformers` and `accelerate`?
> 
> ```shell
> pip install --upgrade accelerate transformers
> ```

yeap, I found that the best paired version is accelerate==0.18.0 and transformers==4.29.1 ! thanks!
