### ISSUE TITLE
suboptimal text getting generated in comparison to spaces demo.

### ISSUE THREAD

**Issue by prasad4fun** [lvwerra/trl#369]
> Awesome! This is great to hear! Feel free to close the issue!

Hi @younesbelkada , i used below code for inference on merged RL adapter with HF-LLAMA model.
```
    model = AutoModelForCausalLMWithValueHead.from_pretrained(rl_model_pth, 
                                                          load_in_8bit=True,
                                                          peft_config=lora_config,).to(device)
    tokenizer = LlamaTokenizer.from_pretrained("hf-internal-testing/llama-tokenizer")
    query_txt = "<random question here>"
    query_tensor = tokenizer.encode(query_txt, return_tensors="pt").to(device)

    response_tensor = respond_to_batch(model, query_tensor)
    response_txt = tokenizer.decode(response_tensor[0,:])
```

The response seem to be mostly short, whereas in stack-llama rl_training.py i could see ppo_trainer.generate in combination of length sampler getting used for text generation.
Also in gradio demo, there are additional params(temperature, max new tokens..) to control generation.

Could you please suggest how to use these additional params, respond_to_batch seem to be limited.

_Originally posted by @prasad4fun in https://github.com/lvwerra/trl/issues/347#issuecomment-1546322550_

**Comment by prasad4fun** [comment]
> Hi @prasad4fun To generate text using that model, you should call `generate` instead of `respond_to_batch`. Please refer to the [text generation docs](https://huggingface.co/docs/transformers/main_classes/text_generation) of `transformers`

Thankyou for the suggestion, i have used below settings and its fairly decent.
`model.generate(**inputs, streamer=streamer, temperature=0.9,  max_new_tokens=256, top_p=0.970, repetition_penalty=1.2)`

**Comment by younesbelkada** [comment]
Awesome! Closing the issue for now, assuming this has been fixed. Feel free to re-open if you don't think so
