### ISSUE TITLE
in merge_peft_adapter.py, why not merge lora model's weights  into the base model?

### ISSUE THREAD

**Issue by aling1472** [lvwerra/trl#370]
`model = PeftModel.from_pretrained(model, peft_model_id)
model.eval()

key_list = [key for key, _ in model.base_model.model.named_modules() if "lora" not in key]
for key in key_list:
    parent, target, target_name = model.base_model._get_submodules(key)
    if isinstance(target, peft.tuners.lora.Linear):
        bias = target.bias is not None
        new_module = torch.nn.Linear(target.in_features, target.out_features, bias=bias)
        model.base_model._replace_module(parent, target_name, new_module, target)

model = model.base_model.model

model.push_to_hub(f"{script_args.model_name}-adapter-merged", use_temp_dir=False)
`

the code :new_module = torch.nn.Linear(target.in_features, target.out_features, bias=bias) not copy weights to new module, just merge the adpter's structure?

**Comment by aling1472** [comment]
it replace weight in model.base_model._replace_module(parent, target_name, new_module, target)

**Comment by SangMyeongWoh** [comment]
> it replace weight in model.base_model._replace_module(parent, target_name, new_module, target)

can you explain more about this?? I also have trouble in understanding this merging process. 
As I inspect code related with this, I still cannot find the weight copying code.
