### ISSUE TITLE
Why「ppo_trainer.generate 」report the following error？ Please help.

### ISSUE THREAD

**Issue by jerry1993-tech** [lvwerra/trl#372]
`
response_tensors = ppo_trainer.generate(
        question_tensors,
        return_prompt=False,
        length_sampler=output_length_sampler,
        **generation_kwargs,
    )
`

![截屏2023-05-17 18 34 15](https://github.com/lvwerra/trl/assets/26736518/d098a172-5a0f-4a40-b3cf-af3b8bd07b53)
![截屏2023-05-17 18 36 01](https://github.com/lvwerra/trl/assets/26736518/eb5039a8-625f-4631-bb9b-c8d8f24abe6d)

**Comment by younesbelkada** [comment]
Hi @xuyingjie521 
You are probably using some input ids that are out of the vocabulary, what model are you using and which tokenizer are you using?

**Comment by younesbelkada** [comment]
Hmm, can you try to run the same script on CPU? Usually the error traces are much better if you re-run the same script on CPU when getting CUDA device side assert errors

**Comment by xuyingjie521** [comment]
> Hmm, can you try to run the same script on CPU? Usually the error traces are much better if you re-run the same script on CPU when getting CUDA device side assert errors

 I haven't tried it yet. Have you run the rl_trianing.py script, what model do you use, can it run on the GPU? How is the effect?
