### ISSUE TITLE
Unavailable not pass Dataset, because of warning issue

### ISSUE THREAD

**Issue by Myashka** [lvwerra/trl#374]
If I would not pass Dataset to PPOTrainer, than it cause a warning:
![image](https://github.com/lvwerra/trl/assets/57448108/b135d184-7dd0-4ec4-98cf-6bfec4d20660)

It lead to error:
![image](https://github.com/lvwerra/trl/assets/57448108/ba309d26-5f45-488b-9746-8cd96fee4935)

**Comment by younesbelkada** [comment]
Hi @Myashka 
Thanks for pointing out the issue! Just made: https://github.com/lvwerra/trl/pull/377 - if you install `trl` from source, the error should disappear
