### ISSUE TITLE
is there a code example for this? Fine-tuning 20B LLMs with RLHF on a 24GB consumer GPU

### ISSUE THREAD

**Issue by shan23chen** [lvwerra/trl#384]
https://huggingface.co/blog/trl-peft
thank you!

**Comment by Noyce765103** [comment]
mark

**Comment by juan-cytora** [comment]
Examples at the top of https://huggingface.co/docs/trl/sentiment_tuning_peft

**Comment by younesbelkada** [comment]
Hey there! 
The relevant examples should be here! https://github.com/lvwerra/trl/tree/main/examples/sentiment/scripts/gpt-neox-20b_peft 
Closing for now, feel free to re-open if you have more questions

**Comment by o-github-o** [comment]
the code has been removed? can not find the code~

**Comment by lvwerra** [comment]
Indeed we removed it for better maintainability in favour of the more general scripts in the examples folder. You can still find the old code here: https://github.com/lvwerra/trl/tree/v0.4.7/examples/sentiment/scripts/gpt-neox-20b_peft
