### ISSUE TITLE
「RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Half」When I run rf_training.py I get this error?

### ISSUE THREAD

**Issue by jerry1993-tech** [lvwerra/trl#385]
![image](https://github.com/lvwerra/trl/assets/26736518/f0e9be51-28d4-44a9-8b35-2f4cd1eeb6ca)

**Comment by lvwerra** [comment]
Can you provide a minimal reproducible example for the issue?

**Comment by xuyingjie521** [comment]
> Can you provide a minimal reproducible example for the issue?

Thank you for your reply！I have solved this problem by upgrading transformers and accelerate to the latest version. 😄
