### ISSUE TITLE
Lora weights are not merged properly in merge_peft_adapter

### ISSUE THREAD

**Issue by vvasily** [lvwerra/trl#386]
It seems that merge_peft_adapter doesn't work properly. Base and output models will be with the same weights.

Weights of Lora are not merged and at least `target.merge()` should be added before this line.
https://github.com/lvwerra/trl/blob/25fa1bd8803c9998d95a3c38b2bb27a85235ce7b/examples/stack_llama/scripts/merge_peft_adapter.py#L58

**Comment by SangMyeongWoh** [comment]
I also have same think with you.
target.merge() should be called somewhere.

**Comment by younesbelkada** [comment]
Hi 
If you use the latest version of `peft` you can just call `model.merge_and_unload()` and the model will be automatically merged. Let us know if you face some issues with that
