### ISSUE TITLE
When to use SFTTrainer vs Trainer?

### ISSUE THREAD

**Issue by austinmw** [lvwerra/trl#388]
In the recent [QLoRA blog post ](https://huggingface.co/blog/4bit-transformers-bitsandbytes), the Colab notebooks used the standard `Trainer` class, however `SFTTrainer` was mentioned briefly at the end of the post. Why wasn't it used in the Colab notebooks associated with this blog post, and when would you advise using it over `Trainer`?

**Comment by lvwerra** [comment]
The `SFTTrainer` is mainly a helper class specifically designed to do SFT while the `Trainer` is more general. E.g. The you can provide the `SFTTrainer` with just a text dataset and a model and you can start training with methods such as packing. Packing is not implemented in the `Trainer` and you also need to tokenize in advance.

Hope this helps!

**Comment by austinmw** [comment]
Thanks, appreciate your response!
