### ISSUE TITLE
Support for CodeGenForCausalLM

### ISSUE THREAD

**Issue by ZhengYang** [lvwerra/trl#403]
I'm trying to use trl for code generation tasks, but unfortunately encountered the error below.

```
ValueError: model must be a PreTrainedModelWrapper, got <class 
'transformers.models.codegen.modeling_codegen.CodeGenForCausalLM'> - supported architectures are: (<class 
'trl.models.modeling_value_head.AutoModelForCausalLMWithValueHead'>, <class 
'trl.models.modeling_value_head.AutoModelForSeq2SeqLMWithValueHead'>)
```

I wanted to understand how much work is required to fit codegen models into the trl's architecture.

**Comment by mnoukhov** [comment]
The `AutoModelForCausalLMWithValueHead` wraps an `AutoModel` and I think you can use `CodeGen` there. What is the exact code you're using / model you're calling

**Comment by ZhengYang** [comment]
Thanks for chiming in! Yes, I figured that out yesterday. Using `AutoModelForCausalLMWithValueHead` to wrap the codegen model seems to work. 
The code is very exploratory, with an approach resembling Salesforce CodeRL paper. The model I'm using is `codegen-350M-mono` from Salesforce.
