### ISSUE TITLE
StackLLAMA examples uses sentiment model as reward model

### ISSUE THREAD

**Issue by jvhoffbauer** [lvwerra/trl#415]
The script to train the StackLLAMA model uses a sentiment pipeline for training the reward model while it should use the model that was trained before. 

https://github.com/lvwerra/trl/blob/main/examples/stack_llama/scripts/rl_training.py#L216

**Comment by mnoukhov** [comment]
The "sentiment" pipeline is not training but an inference pipeline that outputs the scalar reward. It does use the reward model trained from the previous step.

**Comment by jvhoffbauer** [comment]
Understood! Does it help if I add a comment to explain?

**Comment by lvwerra** [comment]
Feel free to add a comment to clarify. Closing the issue.
