### ISSUE TITLE
[BUG] RuntimeError: inflight params error when using DeepSpeed for Reinforcement Learning

### ISSUE THREAD

**Issue by vivek-media** [lvwerra/trl#430]
**I am getting this error while using TRL for T5 Model (and other Seq2seq models too) with PEFT on deepspeed stage 3.**

![image](https://github.com/lvwerra/trl/assets/136303581/a06d7ed1-23fa-4677-82e4-c72d67890efa)

RL with PEFT is working fine for CAUSAL models, but not working for SEQ2SEQ models, on deepspeed stage 3. 
(It was working fine with stage 2).

**Kindly anyone help me with this issue?**

_Also there is no example of PEFT with SEQ2SEQ model, can anyone provide me the correct example for it?_

**Comment by lvwerra** [comment]
Also I am closing this in favour of #378 - could you please report there?

**Comment by vivek-media** [comment]
Hi @lvwerra ,
I guess that issue #378 is different. It is a issue in saving the model, and I am facing issue in training(RL) a Seq2seq models (say T5) with peft on deepspeed stage 3.

**To Reproduce the issue** 

1. I used examples/sentiment/scripts/gpt2-sentiment_peft.py
2. Replace `AutoModelForCausalLMWithValueHead` with `AutoModelForSeq2SeqLMWithValueHead` at line 24, and line 151.
3.  Replace task_type `CAUSAL_LM` with `SEQ_2_SEQ_LM` in line 148.
4. Change model name to T5 (or any other Seq2Seq model).
5. Run it as `accelerate launch my-script.py`

**Error:** RuntimeError: inflight params [<bound method Init ...

![image](https://github.com/lvwerra/trl/assets/136303581/50785bd5-dab5-40d5-b91e-5d851ee4cb9c)

It is similar issue as reported in deepspeed (https://github.com/microsoft/DeepSpeed/issues/3156), but I tried to upgrade as well as used different versions of deepspeed, but problem persist.

TRL with Peft example with GPT2 works fine on deepspeed, So I guess it may be issue with trl library.

Can you help me in this, or provide an example on how to run trl with peft with deepspeed stage 3?

**Comment by vivek-media** [comment]
Please find the Traceback.

<img width="769" alt="image" src="https://github.com/lvwerra/trl/assets/136303581/8e5541fe-c9d5-4e53-a2e2-5d55a08bcd57">
<img width="750" alt="image" src="https://github.com/lvwerra/trl/assets/136303581/469a8482-ccf7-43e5-a0ea-c1c4a2af7b9a">

<img width="1090" alt="image" src="https://github.com/lvwerra/trl/assets/136303581/817f7f3e-f021-4b23-b2f8-f4f8b0978bb5">

I am using Python 3.11.4 with:
transformers==4.30.2 
trl==0.4.5.dev0  
accelerate==0.20.3  
deepspeed==0.9.4   
torch==2.1.0

**Comment by vivek-media** [comment]
I have re-opened the issue in #453 . Please help me this.
