### ISSUE TITLE
Is this supposed to work for AutoModelForSequenceClassification and PEFT TaskType.SEQ_CLS?

### ISSUE THREAD

**Issue by maadnfritz** [lvwerra/trl#433]
The tutorial works fine but when i tried to modify it to perform a Classification task on a standard
Input_ids,  ClassLabel tokenized  dataset i got Trainer initialization errors related to ConstantLengthDataset assumptions in the SFT code. 

Is there some combination of args i need to use? Or is the SFT code not ready to work with AutoModelForSequenceClassification and PEFT TaskType.SEQ_CLS?

fwiw, i also tried to pass in the untokenized Dataset ti the trainer
Dataset({
    features: ['text', 'label'],
    num_rows: 4937
})

'text': Value(dtype='string', id=None),
 'label': ClassLabel(names=[ ...]

That failed because of np padding token specified. so i added 
model.config.pad_token_id = tokenizer.pad_token_id

But then train blows up:
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

So.. just wondering if i should keep trying or if TRL and SFT are not ready for Sequnce Classification ?

**Comment by younesbelkada** [comment]
Hi @maadnfritz 
Thanks for the issue, indeed the SFTTrainer does not support sequence classification with PEFT out of the box as this is a slighly different task. We might need to build a different Trainer for that to make it work

**Comment by maadnfritz** [comment]
thanks for the reply. Great work btw

**Comment by younesbelkada** [comment]
Thanks so much @maadnfritz ! 🎉 
I will close the issue :) feel free to re-open
