### ISSUE TITLE
SFT trainer needs packing=True if passing ConstantLengthDataset

### ISSUE THREAD

**Issue by lopez-hector** [lvwerra/trl#434]
Is this intended? If you pass datasets into SFTTrainer without packing = True it fails.

```
train_dataset: ConstantLengthDataset
eval_dataset: ConstantLengthDataset

trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,)

```

This yields

```
ValueError: You passed `packing=False` to the SFTTrainer, but you didn't pass a `dataset_text_field` or `formatting_func` argument.
```

**Comment by younesbelkada** [comment]
hi @lopez-hector 
Thanks for the issue
Indeed this is expected, if you want to pass a `ConstantLengthDataset` you either need to give the text_field name of that dataset so that during iterations the samples will be properly retireved: https://github.com/lvwerra/trl/blob/61af5f26b626815f3657a08626953fdb682fe6cb/trl/trainer/utils.py#L181 or define your own formatting function that deals with the correct keys of your dataset examples that will be called during iteration as well: https://github.com/lvwerra/trl/blob/61af5f26b626815f3657a08626953fdb682fe6cb/trl/trainer/utils.py#L205

**Comment by lopez-hector** [comment]
This is strange. The SFTtrainer doesn't actually do anything with the dataset if it's already a ConstantLengthDataset. 

https://github.com/lvwerra/trl/blob/61af5f26b626815f3657a08626953fdb682fe6cb/trl/trainer/sft_trainer.py#L217

Here is the function. It's working for me by passing=True but it seems off to pass ```packing=True``` if it's not doing anything in the case that I've already passed a ConstantLengthDataset.

```
def _prepare_dataset(
        self,
        dataset,
        tokenizer,
        packing,
        dataset_text_field,
        max_seq_length,
        formatting_func,
        infinite,
        num_of_sequences,
        chars_per_token,
    ):
        # check if torch dataset / dataloader and do nothing
        if dataset is not None and (
            isinstance(
                dataset,
                (torch.utils.data.IterableDataset, torch.utils.data.Dataset),
            )
        ):
            is_already_dataset = True
        else:
            is_already_dataset = False

        if not packing:
            dataset = self._prepare_non_packed_dataloader(
                tokenizer, dataset, dataset_text_field, max_seq_length, formatting_func
            )

            is_already_dataset = True

        if not is_already_dataset and (dataset_text_field is not None or formatting_func is not None):
            if tokenizer is None:
                raise ValueError(
                    "You need to pass a tokenizer when using the SFT Trainer when passing a `dataset_text_field`."
                )

            dataset = ConstantLengthDataset(
                tokenizer,
                dataset,
                dataset_text_field=dataset_text_field,
                formatting_func=formatting_func,
                seq_length=max_seq_length,
                infinite=infinite,
                num_of_sequences=num_of_sequences,
                chars_per_token=chars_per_token,
                eos_token_id=tokenizer.eos_token_id,
            )

        elif not is_already_dataset and (dataset_text_field is None and formatting_func is None):
            raise ValueError(
                "You need to pass a `dataset_text_field` or `formatting_func` argument to the SFTTrainer if you want to use the `ConstantLengthDataset`."
            )

        return dataset
```

**Comment by younesbelkada** [comment]
I see @lopez-hector 
Thank you very much for detailing the issue, I made https://github.com/lvwerra/trl/pull/442 to fix your issue. Once merged, you will be able to fix the issue by installing TRL from source

**Comment by lopez-hector** [comment]
Thank you @younesbelkada! Quick turnaround 👍

**Comment by younesbelkada** [comment]
Thanks to you for precisely guiding me through the issue!
