### ISSUE TITLE
[BUG] RuntimeError: inflight params error when using DeepSpeed for Reinforcement Learning

### ISSUE THREAD

**Issue by vivek-media** [lvwerra/trl#453]
### I am getting this error while using TRL for T5 Model (and other Seq2seq models too) with PEFT on deepspeed stage 3.

**To Reproduce the issue**

1. I used `examples/sentiment/scripts/gpt2-sentiment_peft.py`
2. Replace `AutoModelForCausalLMWithValueHead` with `AutoModelForSeq2SeqLMWithValueHead` at line 24, and line 151.
3. Replace task_type `CAUSAL_LM` with `SEQ_2_SEQ_LM` in line 148.
4. Change model name to T5 (or any other Seq2Seq model).
5. Run it as `accelerate launch my-script.py`

Error: RuntimeError: inflight params [<bound method Init ...

**Please find the Traceback.**
![image](https://github.com/lvwerra/trl/assets/136303581/86601c6a-bc2b-459f-86ac-4cb0cc85dce6)
![image](https://github.com/lvwerra/trl/assets/136303581/887dde76-3a1c-4c5a-b8c5-f626be9ad521)
![image](https://github.com/lvwerra/trl/assets/136303581/b9fd5c17-2c0b-42c1-8a8c-0f9900ca2b7b)

**It is similar issue as reported in deepspeed (https://github.com/microsoft/DeepSpeed/issues/3156), but I tried to upgrade as well as used different versions of deepspeed, but problem persist.**

TRL with Peft example with GPT2 works fine on deepspeed, So I guess it may be issue with trl library.

**Can you help me in this, or provide an example on how to run trl on T5 with peft with deepspeed stage 3?**

**I am using Python 3.11.4 with:**
transformers==4.30.2
trl==0.4.5.dev0
accelerate==0.20.3
deepspeed==0.9.4
torch==2.1.0

**Comment by vivek-media** [comment]
Same issue (https://github.com/lvwerra/trl/issues/430)

**Comment by yashpreetsinghs** [comment]
+1 Facing similar issue with bigger models on Deepspeed Stage 3.

**Comment by ZJXNEFU** [comment]
+1

**Comment by Fhujinwu** [comment]
+1，please tell me how to address this issue. "RuntimeError: still have inflight params [<bound method Init._convert_to_deepspeed_param.<locals>.ds_summary of Parameter containing"
