### ISSUE TITLE
Solely using the response in the optimisation step

### ISSUE THREAD

**Issue by TheTahaaa** [lvwerra/trl#458]
Hey guys, 
Sorry for posting this as an 'issue', since It's more like a discussion.

I wonder if could we only give the 'Response' to the active model and reference model in the optimisation step. I mean in the docs, the example defined Query as 'The movie is' and the corresponding response as 'really great', and it makes sense to use Query + Response as a whole complete sentence. However, consider a case where we try to add positive sentiment to the response of queries in a search engine. For example, suppose the Query is 'Who is Cristiano Ronaldo' and the response is 'A footballer', and we want our model to generate something like 'A great and renowned footballer'. As we can see, the Response, in this case, is a complete sentence, so we will get a reasonable likelihood (log probs) for the tokens in the Response if we use it as an input in the optimisation step for KL-div part. 
My question is that in such a case, should we keep feeding Query + Response to the LMs in the optimisation step, or we can only use Response?

Thanks in advance!

**Comment by lvwerra** [comment]
I think you'll always want to use both parts in the optimization steps. We use the log-probs of each token and they can be very different if you don't use the full context when you do the forward pass in the model. However, we already mask out query tokens from the optimization step. Also if you only want to rate the response then you should take care of that with the reward model - e.g. only pass the response to a sentiment classifier. 

Hope that makes sense :)

**Comment by TheTahaaa** [comment]
> I think you'll always want to use both parts in the optimization steps. We use the log-probs of each token and they can be very different if you don't use the full context when you do the forward pass in the model. However, we already mask out query tokens from the optimization step. Also if you only want to rate the response then you should take care of that with the reward model - e.g. only pass the response to a sentiment classifier.
> 
> Hope that makes sense :)

I completely agree with you that incorporating both the Query and Response is crucial for nearly all tasks, including ones like Translation or Paraphrasing.
