### ISSUE TITLE
Getting "ValueError: Asking to pad but the tokenizer does not have a padding token." while running the example on ReadMe.

### ISSUE THREAD

**Issue by Samarendra109** [lvwerra/trl#466]
While running the code given in the ReadME file, I am getting the said error. 

Upon checking online, I found that GPT and GPT2 tokenizers didn't have pad token. So is there something wrong in the trainer code? Please have a look.

**Comment by younesbelkada** [comment]
Hi @Samarendra109 
Can you try to add:
```python
tokenizer.pad_token = tokenizer.eos_token
```
Before running your script?

**Comment by Samarendra109** [comment]
Thanks that fixed it. @younesbelkada btw does the repo has some documentation somewhere?

**Comment by younesbelkada** [comment]
Thanks!
absolutely, the documentation is here: https://huggingface.co/docs/trl/index 
I am closing this issue, feel free to re-open if you have more questions !
