### ISSUE TITLE
Trainer filters out any data != max length

### ISSUE THREAD

**Issue by KMFODA** [lvwerra/trl#467]
Hello, thanks for contributing this amazing repo. I tried using the SFT trainer a few days ago and found that 95% of my data was being filtered out because it's length was != max_length as per this filter statement:

https://github.com/lvwerra/trl/blob/009b82412fe79ea975d2bd72586d03e7fa8724c5/trl/trainer/sft_trainer.py#L296C42-L296C42

Is this the correct filter statement or should it be `if length <= max_length`? If not why do we strip out any data that is != max length?

Thanks in advance.

**Comment by younesbelkada** [comment]
Should be fixed by #481

**Comment by younesbelkada** [comment]
This should be now fixed as #512 being merged. You can now install TRL from source or wait for the next patch release (probably very very soon)
