### ISSUE TITLE
Filter out items that do not contain 'Response' after truncation

### ISSUE THREAD

**Issue by BramVanroy** [lvwerra/trl#477]
@younesbelkada in [this PR](https://github.com/lvwerra/trl/pull/445#issuecomment-1601570179), you asked to include a function to preprocess a dataset so that truncated elements that do not have a 'response' are not included. I am currently using the following methods, which work well. But I am not sure how to include those in the library. I would not add these as collators but keep it as a preprocessing step. So how/where should I add these?

```python
def check_if_response_in_prompt_ids(input_idxs: np.ndarray, response_idxs: np.ndarray):
    """Check whether the response prefix (its tokenized indices) are completely part of the input indices AND
    that there is content after the prompt as well.
    
    This is useful if we use a completion-only collator, which will error if a sample does not have the response prefix.
    This can happen due to truncation in the tokenization process"""
    for idx in np.where(np.atleast_1d(input_idxs == response_idxs[0]))[0]:        
        last_span_idx = idx + len(response_idxs)
        if np.array_equiv(response_idxs, input_idxs[idx:last_span_idx]):
            if last_span_idx < len(input_idxs):
                return True

    return False

def find_suitable_samples(dataset: Dataset, response_prefix: str, dataset_split: str = None):
    """Find samples where, even after tokenization and truncation to the max seq length,
    the response prefix is still fully present."""
    valid_idxs = set()
    
    response_token_ids = tokenizer(response_prefix, add_special_tokens=False, return_tensors="np").input_ids[0]
    for idx, sample in tqdm(enumerate(dataset),
                            desc=f"Processing {dataset_split}" if dataset_split else "Processing",
                            total=len(dataset),
                           leave=False):
        prompt = format_sample(sample["instruction"], sample["input"], sample["output"])
        input_ids = tokenizer(prompt, truncation=True, max_length=max_seq_length, return_tensors="np").input_ids[0]
        
        if check_if_response_in_prompt_ids(input_ids, response_token_ids):
            valid_idxs.add(idx)
    return valid_idxs
```

**Comment by younesbelkada** [comment]
Hi @BramVanroy 
Thanks a lot !
In my opinion these preprocessing methods should live in the SFTTrainer's init method and called only in the case `DataCollatorForCompletionOnlyLM` is passed to the trainer. I can imagine it can be called after properly creating / checking the datasets. What do you think?

**Comment by younesbelkada** [comment]
More precisely right before this line: https://github.com/lvwerra/trl/blob/bbc7eeb29c7de42c93e11579676ecf7078fe88aa/trl/trainer/sft_trainer.py#L197 after making sure the data collator is a `DataCollatorForCompletionOnlyLM`

**Comment by BramVanroy** [comment]
For future readers: as far I know, the current implementation does not verify that batches actually have trainable samples (i.e. sample with non -100 tensors). I currently do not have the time to work on this but in my own code I use https://github.com/lvwerra/trl/issues/477#issue-1779417425 which works well.
