### ISSUE TITLE
 05-gpt2-sentiment-control.ipynb notebook, gpt2_tokeinizer is missing

### ISSUE THREAD

**Issue by saeedashraf** [lvwerra/trl#48]
in 05-gpt2-sentiment-control.ipynb notebook:

ppo_trainer = PPOTrainer(gpt2_model, gpt2_model_ref, **config)

there is a tokenizer argument missing... should be

ppo_trainer = PPOTrainer(gpt2_model, gpt2_model_ref,  gpt2_tokeinizer,  **config)

**Comment by lvwerra** [comment]
Thanks, I'll fix that!

**Comment by lvwerra** [comment]
Should be fixed with #80.
