### ISSUE TITLE
Make Trainers compatible with hyperparameter search (init_model)

### ISSUE THREAD

**Issue by BramVanroy** [lvwerra/trl#484]
In the regular Hugging Face Trainer we can use a hyperparameter search that requires an `init_model` function and `model=None` as input to the trainer. That does not work in the trl trainer, however, since they want to Peftify the model immediately. It is therefore impossible, as far as I can see, to use the hyperparameter search algorithms that are compatible with the `transformers.Trainer` in `trl` Trainers.

**Comment by lvwerra** [comment]
Closing this for now as we don't plan to support it in the near future.
