### ISSUE TITLE
how to change the cache directory when using AutoModelForCausalLMWithValueHead.from_pretrained()

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [lvwerra/trl#520]
I have tried several methods, but it still download to my home directory

**Comment by zyzisastudyreallyhardguy** [comment]
problem solved by modifying the source code

**Comment by younesbelkada** [comment]
hi @zyzisastudyreallyhardguy 
thanks ! Can you share how did you modified the source code so that we can apply the fix for all users?

**Comment by zyzisastudyreallyhardguy** [comment]
for the from_pretrained function in the modeling_base.py. I add code to define the values in pretrained_kwargs.

**Comment by younesbelkada** [comment]
Thanks, can you share a reproducible snippet of your issue?
