### ISSUE TITLE
Negative reward in PPO training

### ISSUE THREAD

**Issue by shadowkiller33** [lvwerra/trl#521]
Hi, I'm trying to reproduce Stack-LLaMa using the default config settings. However, after training hundreds of steps, the reward score remains negative. 
![1689539506953](https://github.com/lvwerra/trl/assets/61814604/f770025f-f973-47e1-87af-e2f4dbf33bbd)

Also, my objectives look strange.
![1689539829480](https://github.com/lvwerra/trl/assets/61814604/da047cec-ecf7-48c7-8f1a-3fb41800b77a)

However, the total loss of PPO looks fine:
![1689539871663](https://github.com/lvwerra/trl/assets/61814604/c8cd39fd-b7fc-450f-913e-b4dfac67f046)

The reward model and SFT model I use are based on https://huggingface.co/trl-lib/llama-7b-se-rm-peft and trl-lib/llama-7b-se-peft. Could some tell me what's wrong with my RL training? Thanks!

**Comment by lvwerra** [comment]
Which script are you using to run this? Have you looked at #401 ?

**Comment by shadowkiller33** [comment]
Yeah, I'm following [mnoukhov](https://github.com/mnoukhov)'s instructions to reproduce Stack-LLaMa, is it possible that these issues are due to V100?
