### ISSUE TITLE
DPO evaluation error---tensors on two devices

### ISSUE THREAD

**Issue by liutianlin0121** [lvwerra/trl#525]
Hi!

Thanks for the awesome codebase. I ran the DPO example `trl/examples/dpo.py` but encountered an error at the evaluation step: `Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

Here is a [colab notebook](https://colab.research.google.com/drive/11AVym7U3gkTn_qTfrnSDtA_AO5_zJkkd?usp=sharing) that shows this problem. To expose the problem faster, I set `training_args.eval_steps = 1`.

To solve it, a hotfix can be adding `.to(self.accelerator.device)` at a few places in [concatenated_forward](https://github.com/lvwerra/trl/blob/main/trl/trainer/dpo_trainer.py#L288-L296):

```python
all_logits = model(
    concatenated_batch["concatenated_input_ids"].to(self.accelerator.device),
    attention_mask=concatenated_batch["concatenated_attention_mask"].to(self.accelerator.device),
).logits.to(torch.float32)
all_logps = self._get_batch_logps(
    all_logits,
    concatenated_batch["concatenated_labels"].to(self.accelerator.device),
    average_log_prob=False,
)
```

However, I am not sure why the trainer does not handle the device change automatically. If this hotfix is fine, I can submit a pull request. Otherwise, I'm also happy to learn how to address this problem more generically.

Tianlin

**Comment by younesbelkada** [comment]
Hi @liutianlin0121 
Thanks very much for the clean reproducer, this sounds like definitely the right fix. Would you mind contributing and opening a PR so that the community can benefit from the fix🙏 
Thanks very much!

**Comment by lvwerra** [comment]
also cc @kashif

**Comment by liutianlin0121** [comment]
Thanks @younesbelkada @lvwerra for the response and @kashif for the fix! Closing the issue.

**Comment by kashif** [comment]
@liutianlin0121  i never tested it on multiple gpus.... so lesson learned! thanks for the report.

BTW as an aside, I love your optimal transport paper, the code is only in jax or also in pytorch?

**Comment by liutianlin0121** [comment]
@kashif Thank you! The implementation of the sparsity-constrained OT is in both Pytorch and Jax. [This repo](https://github.com/liutianlin0121/sparsity-constrained-ot-demo) contains [colab notebook](https://colab.research.google.com/drive/1yxxeqrlKsGrhoqLmY7IjJNgOJnd3Pvu1?usp=sharing) demos of both :-)

**Comment by agokrani** [comment]
Hi @kashif, 

I am trying to run dpo with fsdp and getting similar error again 
 File "/pkg/modal/_container_entrypoint.py", line 349, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 467, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/train.py", line 237, in main
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1864, in _inner_training_loop
    tr_loss += tr_loss_step
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Can you please help?

**Comment by jayachandrakalakutagar** [comment]
> Hi @kashif,
> 
> I am trying to run dpo with fsdp and getting similar error again File "/pkg/modal/_container_entrypoint.py", line 349, in handle_input_exception yield File "/pkg/modal/_container_entrypoint.py", line 467, in run_inputs res = imp_fun.fun(*args, **kwargs) File "/root/train.py", line 237, in main trainer.train() File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train return inner_training_loop( File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1864, in _inner_training_loop tr_loss += tr_loss_step RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> 
> Can you please help?

Hi did you find the soltuion?
