### ISSUE TITLE
example for "Fine-tuning 20B LLMs with RLHF on a 24GB consumer GPU"

### ISSUE THREAD

**Issue by xiaojuntime** [lvwerra/trl#526]
As trl is undergoing heavy development, all the instructions for https://huggingface.co/blog/trl-peft are not applicable.
Is there any doc available for fine-tuning 20B LLM with RLHF on the latest code base?

**Comment by younesbelkada** [comment]
Hi @xiaojuntime 
Thanks very much for brining this up, currently things are much more simpler now (if you use peft>=0.4.0):

- 1- Supervised fine-tuning: Simply run this script: https://github.com/lvwerra/trl/blob/main/examples/scripts/sft_trainer.py and adapt it to your needs (e.g. dataset)
- 2 - for merging adapters: Once the model has been fine-tuned, push the adapter weights locally or on the Hub, and load them back in a PEFT model and just call `model.merge_and_unload()` 

```python
from peft import AutoPeftModelForCausalLM

model_id = "your_peft_model_path"
merged_model_path = "your_merged_model_path"

peft_model = AutoPeftModelForCausalLM.from_pretrained(model_id)
merged_model = peft_model.merge_and_unload()
merged_model.push_to_hub(merged_model_path)
```

- 3 - PPO fine-tuning: Pass to this script https://github.com/lvwerra/trl/blob/main/examples/scripts/sentiment_tuning.py `--use_peft` argument to load adapters. You can adapt it to your needs to load the base model in 8bit or 4bit by passing the argument `load_in_8bit=True` (or `load_in_4bit=True`).

**Comment by younesbelkada** [comment]
Yes it should work out of the box with any HF model I believe, let me know if not!

**Comment by younesbelkada** [comment]
@xiaojuntime I think you are using an old version of PEFT, can you try with

```bash
pip install --upgrade peft
```

**Comment by xiaojuntime** [comment]
@younesbelkada

After I did the upgrade, peft is 0.4.0 now. There is still the same error.

**Comment by younesbelkada** [comment]
Hi @xiaojuntime 

very strange, I could not reproduce on my end; can you try with a smaller model?
```bash
accelerate launch examples/scripts/sft_trainer.py --model_name EleutherAI/gpt-neo-125m --dataset_name imdb --use_peft --batch_size 1 --gradient_accumulation_steps 8
```

**Comment by xiaojuntime** [comment]
@younesbelkada 
Interestingly enough, I can run the command on another system, while the previous system still reported the same problem.

I believe there are some environment issues on the previous system, but no concrete idea how to figure it out. BTW, both the systems have exactly the same packages as following:
accelerate                    0.19.0
bitsandbytes                  0.40.1.post1
peft                          0.5.0.dev0
transformers                  4.27.1
trl                           0.4.8.dev0

**Comment by younesbelkada** [comment]
@xiaojuntime I see this is interesting, did you tried to re-install all these packages in a fresh env on the first system?

**Comment by xiaojuntime** [comment]
Thanks @younesbelkada !
It turns out that "accelerate launch xxxx" have problem on the first system, while "python3 xxxx" is fine.

**Comment by xiaojuntime** [comment]
@younesbelkada When I go further to launch `python3 examples/scripts/sft_trainer.py --model_name EleutherAI/gpt-neox-20b --dataset_name imdb --use_peft --batch_size 1 --gradient_accumulation_steps 8` on the first system. There is OOM issue, is there any parameter to tweak to lower GPU memory consumption?

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:08<00:00,  5.49it/s]
Found cached dataset imdb (/home/eason/.cache/huggingface/datasets/imdb/plain_text/1.0.0/d613c88cf8fa3bab83b4ded3713f1f74830d1100e171db75bbddb80b3345c9c0)
Using pad_token, but it is not set yet.
/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/trl/trainer/sft_trainer.py:159: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
Traceback (most recent call last):                                                                                                                                                                                                                 
  File "/home/eason/workspace/trl/examples/scripts/sft_trainer.py", line 101, in <module>
    trainer = SFTTrainer(
              ^^^^^^^^^^^
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 197, in __init__
    super().__init__(
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/transformers/trainer.py", line 499, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/transformers/trainer.py", line 741, in _move_model_to_device
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/eason/anaconda3/envs/future/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 44.56 GiB total capacity; 44.05 GiB already allocated; 180.25 MiB free; 44.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by xiaojuntime** [comment]
@younesbelkada
After I added "--load_in_8bit" parameter, sft_trainer.py can be successfully launched with command
`python3 examples/scripts/sft_trainer.py --model_name EleutherAI/gpt-neox-20b --dataset_name imdb --use_peft --batch_size 1 --gradient_accumulation_steps 8 --load_in_8bit`

One more thing is that it needs much more iterations say 4686 (and more than 40 hours) than 1849 (around 11 hours) by following command with old clm_finetune_peft_imdb.py:
`python3 clm_finetune_peft_imdb.py  --model_name_or_path=EleutherAI/gpt-neox-20b  --per_device_train_batch_size=1  --gradient_accumulation_steps=8  --warmup_steps=50  --num_train_epochs=1.0  --learning_rate=5e-5  --logging_steps=1  --output_dir=./gpt-neox-20b-peft  --block_size=512`

**Comment by xiaojuntime** [comment]
Sorry, I should set num_train_epochs=1 in TrainingArguments.

**Comment by younesbelkada** [comment]
Sorry for my late reply, thanks for investigating further, does everything works now?

**Comment by xiaojuntime** [comment]
Thanks @younesbelkada a lot!
Yes, it works now.

One more thing, when I run `
python3 examples/scripts/sft_trainer.py --model_name EleutherAI/gpt-neox-20b --dataset_name imdb --use_peft --batch_size 1 --gradient_accumulation_steps 8 --load_in_8bit` with num_train_epochs=1, it seems it consumes 31098MiB GPU memory, is there any way to reduce the GPU consumption?

**Comment by younesbelkada** [comment]
Thanks! You can reduce memeory by using 4bit instead of 8bit for instance, i think replacing the flag `--load_in_8bit` by `--load_in_4bit` should do the trick

**Comment by xiaojuntime** [comment]
IIRC, clm_finetune_peft_imdb.py (should use 8bit by default) only consumed around 25GB.

**Comment by xiaojuntime** [comment]
Yes, they are using different max_seq_length. After I changed to 512, the GPU mem consumptions were almost the same.

**Comment by xiaojuntime** [comment]
Thanks @younesbelkada! One more question, is there a list of models supported by TRL?

**Comment by xiaojuntime** [comment]
@younesbelkada
Is there any parameter to lower GPU mem consumption for sentiment_tuning.py just like --load_in_8bit for sft_trainer.py? I met GPU OOM issue when doing sentiment_tuning.py on the merged sft model.

**Comment by xiaojuntime** [comment]
@younesbelkada 

One more question on the model size after step 2.

In step 1, I used `python3 examples/scripts/sft_trainer.py --model_name EleutherAI/gpt-neox-20b --dataset_name imdb --use_peft --batch_size 1 --gradient_accumulation_steps 8 --load_in_8bit`, and got following output files under output/checkpoint-1500, e.g.:

> -rw-rw-r-- 1 guest guest       440 Jul 24 09:07 adapter_config.json
-rw-rw-r-- 1 guest guest  69238585 Jul 24 09:07 adapter_model.bin
-rw-rw-r-- 1 guest guest 138464261 Jul 24 09:07 optimizer.pt
-rw-rw-r-- 1 guest guest       795 Jul 24 09:07 README.md
-rw-rw-r-- 1 guest guest     14575 Jul 24 09:07 rng_state.pth
-rw-rw-r-- 1 guest guest       627 Jul 24 09:07 scheduler.pt
-rw-rw-r-- 1 guest guest       131 Jul 24 09:07 special_tokens_map.json
-rw-rw-r-- 1 guest guest       264 Jul 24 09:07 tokenizer_config.json
-rw-rw-r-- 1 guest guest   2113738 Jul 24 09:07 tokenizer.json
-rw-rw-r-- 1 guest guest       715 Jul 24 09:07 trainer_state.json
-rw-rw-r-- 1 guest guest      3963 Jul 24 09:07 training_args.bin

In step 2, I used following script to merge the model:
```
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer

model_id = "./output/checkpoint-1500"
merged_model_path = "xiaojuntime/peft-merged"

tokenizer = AutoTokenizer.from_pretrained(model_id)
peft_model = AutoPeftModelForCausalLM.from_pretrained(model_id)
merged_model = peft_model.merge_and_unload()
merged_model.push_to_hub(merged_model_path)
tokenizer.push_to_hub(merged_model_path)
```

I found it's quite large (more than 80GB) for the uploaded model https://huggingface.co/xiaojuntime/peft-merged/tree/main, is this reasonable?

**Comment by younesbelkada** [comment]
Hi @xiaojuntime 
Thanks for all the question, let me try to reply to them one by one:

> Thanks @younesbelkada! One more question, is there a list of models supported by TRL?

All decoder & encoder-decoder models from transformers library should be supported

> Is there any parameter to lower GPU mem consumption for sentiment_tuning.py just like --load_in_8bit for sft_trainer.py? I met GPU OOM issue when doing sentiment_tuning.py on the merged sft model.

You could try `--load_in_4bit` that will load the base model in 4bit precision instead of 8bit, this should lead to slower memory requirement

> One more question on the model size after step 2. ..

This is expected, in the script you shared you are loading the 20B model in full precision. A 20B model will have 80GB in total as each parameter will have 4 bytes. You can load the base model in half-precision (for example in bfloat16), merge it and push it. That model will take 40GB in total 

```python
import torch
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer

model_id = "./output/checkpoint-1500"
merged_model_path = "xiaojuntime/peft-merged"

tokenizer = AutoTokenizer.from_pretrained(model_id)
peft_model = AutoPeftModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16)
merged_model = peft_model.merge_and_unload()
merged_model.push_to_hub(merged_model_path)
tokenizer.push_to_hub(merged_model_path)
```

Hope this helps!

**Comment by younesbelkada** [comment]
> Sorry, I meant there is no --load_in_4bit or --load_in_8bit parameters for sentiment_tuning.py, or how can i specify this for sentiment_tuning.py?

Yes you are right, one needs to pass `load_in_8bit` / `load_in_4bit` here: https://github.com/lvwerra/trl/blob/51d5f08d88460a68fab143c22e58c72e46beffb9/examples/scripts/sentiment_tuning.py#L151

> Is there any way to load model in 8 bits mode?

You can but merging adapters in 8bit mode is not supported :/

**Comment by xiaojuntime** [comment]
Thanks @younesbelkada, it works!

BTW, in step 2 for the merging, there is no GPU involved, right?

**Comment by xiaojuntime** [comment]
@younesbelkada 

In step #3, it seems the training cannot be converged:
```
ppo_trainer.py:1157: UserWarning: KL divergence is starting to become negative: -3.63 - this might be a precursor for failed training. sometimes this happens because the generation kwargs are not correctly set. Please make sure that the generation kwargs are set correctly, or review your training hyperparameters.
```

Do you have any suggestion for this? I just used the following command:
```
python3 examples/scripts/sentiment_tuning.py --model_name xiaojuntime/peft-merged --use_peft --mini_batch_size 1 --batch_size 1 --gradient_accumulation_steps 8
```

The only change I did is:
```
--- a/examples/scripts/sentiment_tuning.py
+++ b/examples/scripts/sentiment_tuning.py
@@ -149,6 +149,7 @@ model = trl_model_class.from_pretrained(
     config.model_name,
     device_map=device_map,
     peft_config=peft_config,
+    load_in_8bit=True,
 )
```

**Comment by younesbelkada** [comment]
hi @xiaojuntime 
I suggest you train it with larger batch size and mini batch size (e.g. 32 / 4)

**Comment by xiaojuntime** [comment]
Hi @younesbelkada 
I launched a train with batch size/mini batch size equal to 32/4, and it's over 5 hours and still running, no KL divergence warning so far. But the old way (by gpt-neo-20b_sentiment_peft.py) can finish within 3 hours.

**Comment by xiaojuntime** [comment]
> Hi @younesbelkada I launched a train with batch size/mini batch size equal to 32/4, and it's over 5 hours and still running, no KL divergence warning so far. But the old way (by gpt-neo-20b_sentiment_peft.py) can finish within 3 hours.

Update, it's finished in almost 12 hours, good news is no KL divergence warning. Don't know if the time is reasonable on a RTX A6000.

**Comment by xiaojuntime** [comment]
@younesbelkada 

One more thing, I appended following to the end of examples/scripts/sentiment_tuning.py
```
model.push_to_hub("xiaojuntime/adapted-ppo")
tokenizer.push_to_hub("xiaojuntime/adapted-ppo")
```

But there is no config.json in the hf model repo, anything I missed?

**Comment by xiaojuntime** [comment]
@younesbelkada 

It seems that if I have "--use_peft" in sentiment_tuning.py cmd line, the saved model doesn't have config.json. (seems only adapter info):
```
-rw-rw-r-- 1 eason eason      461 Jul 27 23:01 adapter_config.json
-rw-rw-r-- 1 eason eason 33600461 Jul 27 23:01 adapter_model.bin
-rw-rw-r-- 1 eason eason    17471 Jul 27 23:01 pytorch_model.bin
-rw-rw-r-- 1 eason eason      435 Jul 27 23:01 README.md
-rw-rw-r-- 1 eason eason      437 Jul 27 23:01 special_tokens_map.json
-rw-rw-r-- 1 eason eason      719 Jul 27 23:01 tokenizer_config.json
-rw-rw-r-- 1 eason eason  1842865 Jul 27 23:01 tokenizer.json
```

BTW, examples/notebooks/gpt2-sentiment.ipynb also doesn't include peft_config when doing from_pretrained().

But if I don't use "--use_peft", it's going to consume a lot of GPU memory which causes OOM.
Do you have any idea how to use "--use_peft" and generate config.json?

**Comment by xiaojuntime** [comment]
@younesbelkada 
Should I use ```merge_and_unload()``` you mentioned before to merge the model after PPO with the model before the PPO?

**Comment by xiaojuntime** [comment]
> @younesbelkada Should I use `merge_and_unload()` you mentioned before to merge the model after PPO with the model before the PPO?

Yes, it works! Thanks @younesbelkada a lot for the help!
I am going to close the issue now.
