### ISSUE TITLE
Train or fine tune language model with DPO

### ISSUE THREAD

**Issue by imrankh46** [lvwerra/trl#533]
Hi, I want to train language model with DPO, but I don't know how to do this. 
Is trl support DPO?

I need example..

**Comment by tomaarsen** [comment]
Hello!

Please have a look at this example script: https://github.com/lvwerra/trl/blob/main/examples/dpo.py
And this documentation: https://huggingface.co/docs/trl/main/en/dpo_trainer

- Tom Aarsen

**Comment by imrankh46** [comment]
> Hello!
> 
> Please have a look at this example script: https://github.com/lvwerra/trl/blob/main/examples/dpo.py And this documentation: https://huggingface.co/docs/trl/main/en/dpo_trainer
> 
> * Tom Aarsen

Thank you

**Comment by tomaarsen** [comment]
Hello!

DPO has not been released in the latest version of TRL yet, so you have to use the "cutting edge" version from the GitHub instead:
```
pip install -U git+https://github.com/lvwerra/trl
```

- Tom Aarsen

**Comment by lvwerra** [comment]
There should be a release in the next few days :)
