### ISSUE TITLE
Question about the `rel_model` in ppo_trainer

### ISSUE THREAD

**Issue by beyondguo** [lvwerra/trl#536]
Hi, thanks for your great tool!

I'm tuning the ppo and I want to set my **peft model (which is base model with a SFT lora adapter)** as the **ref_model**, but it seems that the peft model is not supported for ref_model, according to https://github.com/lvwerra/trl/blob/main/trl/trainer/ppo_trainer.py#L218C33-L218C33

could you tell me why this is not supported?

In my situation, my model for ppo training is set up like this:"
```python

# load the base model
base_model_for_PPO = AutoModelForCausalLM.from_pretrained(
    script_args.base_model_name,
    trust_remote_code=True,
    torch_dtype=torch.bfloat16, 
    device_map='auto'
    )
# install the lora modules
base_model_for_PPO_with_sft_lora = PeftModel.from_pretrained(
    base_model_for_PPO, 
    script_args.sft_model_lora_path
    )
# wrap with the AutoModelForCausalLMWithValueHead wrapper
ppo_model = AutoModelForCausalLMWithValueHead.from_pretrained(
    base_model_for_PPO_with_sft_lora
)
# make the lora modules trainable
for name, param in ppo_model.named_parameters():
    if 'lora' in name:
        param.requires_grad = True
```

and I want to set the `ppo_model` in my code to be the ref_model as well.

**Comment by lvwerra** [comment]
Hi @beyondguo, the way we use `peft` for the reference and active model is the following: start with a base model and add an adapter on top of it. When we disable the adapter we get the reference model and when we activate it we get the active model. The issue with having a base model that already has an adapter is that we would need to add an adapter on top of the adapter. Thus it is best to merge the adapter before the RL training and train a new one on top of it. Hope that makes sense!

**Comment by beyondguo** [comment]
Thanks @lvwerra , actually I'm not `add an adapter on top of the adapter`, instead, I want to `continue training the previous SFT adapter` with PPO. That's why I want ref model to support a peft model.

**Comment by beyondguo** [comment]
Got it. Thanks!

**Comment by lvwerra** [comment]
Cool, closing this for now, feel free to open should there be any follow up questions!
