### ISSUE TITLE
Can we use GPT - J [EleutherAI/gpt-j-6B] ?  Instead of GPT 2 ? trl is only available for GPT 2 

### ISSUE THREAD

**Issue by 22Mukesh22** [lvwerra/trl#54]
Can we use GPT - J [EleutherAI/gpt-j-6B] ?  Instead of GPT 2 ? trl is only available for GPT 2 
Please let me know

**Comment by lvwerra** [comment]
Coming soon - see #53!

**Comment by 22Mukesh22** [comment]
That's Great , waiting for GPT-J to learn through human feedback ?
But what in your thought, Bert classifier will be able to reward the text generated ?? Or there will be any other reward model who can give the score for the generated task.

**Comment by conceptofmind** [comment]
Has #53 been merged?

**Comment by lvwerra** [comment]
Yes, that should work!
