### ISSUE TITLE
Faced the problem of rising KL: PPO training with three solid sentiments

### ISSUE THREAD

**Issue by z00logist** [lvwerra/trl#56]
Thank you very much for making such an awesome framework!
Right now I am fine tuning[ ruGPT3small](https://huggingface.co/sberbank-ai/rugpt3small_based_on_gpt2)(125 million parameters) with [Bert ](https://huggingface.co/cointegrated/rubert-tiny2)for sentiment classification in order to get controllable text generation. I follow every step in [your notebook](https://lvwerra.github.io/trl/05-gpt2-sentiment-control). My dataset is also cinema reviews but not from IMDB. Moreover, this dataset unlike IMDB's one is divided into three sentiments (positive, negative, neutral). Important to mention that these sentiments were given not automaticaly but by the user who wrote the review (so, there could not probably be anything wrong with that).
I faced the problem of rising KL.
![2022-12-24 17 23 19](https://user-images.githubusercontent.com/121341170/209439920-8d1c969f-da38-4803-bc46-fc90c4a93ce1.jpg)
I tried many approaches. For example, I rewrote the reward function: ![telegram-cloud-photo-size-2-5276317222798739103-y](https://user-images.githubusercontent.com/121341170/209439941-2dff14d0-c2ad-4c78-9127-1b2722f13abc.jpg)
I do not quite understand why it happens but I suggest that the problem lies in neutral sentiment (as you do not have it in the dataset and I do). Here is my  reward distribution:
![telegram-cloud-photo-size-2-5276317222798739102-y](https://user-images.githubusercontent.com/121341170/209439972-0e3738ef-2f2b-487f-8cf4-6496cb0ccecd.jpg)

Maybe, you could give me an idea how to organise  reward function considering the fact that i have three solid sentiments.
I also wanted to ask: is it a mandatory to train GPT/BERT only on one epoch before implementing them together? Or can I train them e.g. on 5 epochs?

**Comment by lvwerra** [comment]
Also the KL-divergence is allowed to raise but the controller should at some point bring it back down.
