### ISSUE TITLE
how to use SFTTrainer for multi turns dialogue?

### ISSUE THREAD

**Issue by moseshu** [lvwerra/trl#591]
I wanto use SFTTrainer to train a multi turns dialogues. does it apply to llama-2-7b-cha-hf? is it same to llama-2-7b-hf for instruction tune?
my dataset is multi turns dialogues. 
the prompt is:
```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ user_msg_1 }} [/INST] {{ model_answer_1 }} </s><s>[INST] {{ user_msg_2 }} [/INST] {{ model_answer_2 }} </s><s>[INST] {{ user_msg_3 }} [/INST]

```

**Comment by gaetanlop** [comment]
Hello @moseshu, there is an example on how to do this in this page: [https://huggingface.co/docs/trl/main/en/sft_trainer](url). It is very similar to instruction tuning, you just need to pass an instruction template and a response template to the DataCollatorForCompletionOnlyLM.

**Comment by moseshu** [comment]
> Hello @moseshu, there is an example on how to do this in this page: https://huggingface.co/docs/trl/main/en/sft_trainer. It is very similar to instruction tuning, you just need to pass an instruction template and a response template to the DataCollatorForCompletionOnlyLM. You can look at #456 for more information.

many thanks
