### ISSUE TITLE
How to run using multi-GPUs?

### ISSUE THREAD

**Issue by jyC23333** [lvwerra/trl#597]
Hi, I'm not so familiar with the training method using multi-GPUs.

I have a machine with 8 A100s, what should I do to full params SFT a llama2-7B model? 
How to use the trl tool?

Thanks.

**Comment by lvwerra** [comment]
You don't have to change anything in the way your script is structured and just change the setting in `acclerate config`. Usually a good idea to get things to work on a single GPU first, though! See this guide: https://huggingface.co/docs/trl/main/en/customization#run-on-multiple-gpus-nodes

**Comment by jyC23333** [comment]
@lvwerra I got this:
accelerae config:
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 7
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

run command
```
accelerate launch  trl/examples/scripts/sft_trainer.py \
    --model_name models_hf/llama2-7B-hf/ \
    --dataset_name timdettmers/openassistant-guanaco \
    --batch_size 3 \
    --gradient_accumulation_steps 2
```

Finally, Out of Memory:
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 4; 79.15 GiB total capacity; 76.49 GiB already allocated; 14.38 MiB free; 77.25 GiB reserved in total by PyTorch) If reserved memory is >> 
allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Does full params finetune cost so much?

**Comment by lvwerra** [comment]
Yes :) You probably may want to use PEFT to help with that!

**Comment by cwzhao** [comment]
Same issue here. I think if we enable DeepSpeed by accelerate, it should work on 8 A100s.

**Comment by jyC23333** [comment]
@cwzhao Another full params finetune method is [llama-recipe](https://github.com/facebookresearch/llama-recipes).
And it works for llama-2-7B.

I don't know if there are some differences between the two methods. @lvwerra

**Comment by liebkne** [comment]
I got this when using accelerate

```
ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}
Using pad_token, but it is not set yet.
```
