### ISSUE TITLE
Allow already tokenized sequences for `response_template` in `DataCollatorForCompletionOnlyLM`

### ISSUE THREAD

**Issue by ivsanro1** [lvwerra/trl#598]
# Problem description

Hello. I would like to point out what's likely to be an issue when using trl to finetune Llama2 with Alpaca instruction format.

My problem is that the underlying tokenization for the `response_template` does not match the tokenization of the same string with the extra context of the prompt. I'll give an example:

```python
tokenizer = AutoTokenizer.from_pretrained( "meta-llama/Llama-2-7b-hf")

def print_tokenize(txt):
    for el in list(zip(tokenizer.tokenize(txt), tokenizer(txt)['input_ids'])):
        print(el)

print_tokenize('...end of some instruction.\n\n### Assistant: answer')

>>> ('▁...', 1)
('end', 2023)
('▁of', 355)
('▁some', 310)
('▁instruction', 777)
('.', 15278)
('<0x0A>', 29889)
('<0x0A>', 13)
('##', 13)
('#', 2277)
('▁Ass', 29937)
('istant', 4007)
(':', 22137)
('▁answer', 29901)
```

So, the expected sequence of input_ids to match `response_template` if I set `response_template="\n### Assistant:` would be:

```python
('<0x0A>', 13)
('##', 13)
('#', 2277)
('▁Ass', 29937)
('istant', 4007)
(':', 22137)
```

However, due to the nature of this tokenizer, the first "\n" is tokenized differently from subsequent (token id 29889 vs 13) which makes sense because it means different things, but this makes it impossible to match the original prompt if it has several "\n":

```python3
data_collator = DataCollatorForCompletionOnlyLM(
    "\n### Assistant:",
    tokenizer,
)
```

```
RuntimeError: Could not find response key [29871, 13, 2277, 29937, 4007, 22137] in token IDs tensor([    1,   835,  2184, 
```
See how "\n### Assistant:" gets tokenized to `[29871, 13, 2277, 29937, 4007, 22137]` instead of the expected `[13, 13, 2277, 29937, 4007, 22137]`, because of the lack of context of `response_template`.

The same happens if I don't include "\n" in the `response_template`, but in that case it happens with the "###", which is tokenized differently, showing that this problem happens in several scenarios.

I saw in https://huggingface.co/docs/trl/sft_trainer that one "trick" is to put a space before the Assistant/Answer prompt (" ### Answer:"). But I was wondering if some fix could be implemented so that it would not be necessary to modify the dataset.

# Proposal

I propose to slightly modify the implementation of `DataCollatorForCompletionOnlyLM` to allow tokenized inputs. Example:

```python
data_collator = DataCollatorForCompletionOnlyLM(
    tokenizer('\n\n### Assistant:')['input_ids'][2:],
    tokenizer,
)
```

**Comment by ivsanro1** [comment]
I've managed to fix this locally slightly modifying the implementation. Please tell me if it's worth submitting a PR for it

**Comment by younesbelkada** [comment]
hi @ivsanro1 
Thanks for the heads up!
In my case I think I have managed to overcome that by using `"\n### Assistant: "` instead of `"\n### Assistant:"` as response template (adding an extra space). Let me know if this fixes your issue. Also can you elaborate more on the slight modification you have mentioned?

**Comment by ivsanro1** [comment]
Hi @younesbelkada, thanks for the suggestion. Unfortunately, since the problem is how the tokenizer tokenizes the first characters differently because lack of context in `response_template`, your suggestion does not solve the problem. Here's a test:

```python
from transformers import AutoTokenizer

MODEL_NAME = "meta-llama/Llama-2-7b-hf"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

text_w_context = "...left context.\n### Assistant: Right context..."
response_template = "\n### Assistant: "

def test_response_template_within_text_w_context(response_template):
    response_token_ids = tokenizer.encode(response_template, add_special_tokens=False)
    text_w_context_token_ids = tokenizer.encode(text_w_context, add_special_tokens=False)
    print(f"response_token_ids: {response_token_ids}")
    print(f"text_w_context_token_ids: {text_w_context_token_ids}")
    assert str(response_token_ids)[1:-1] in str(text_w_context_token_ids)  # is response_tokens a list contained in text_w_context_token_ids?

test_response_template_within_text_w_context("\n### Assistant: ")  # Fails
test_response_template_within_text_w_context("\n### Assistant:")  # Fails
```

First test ("\n### Assistant: ") prints (see how `29871` != `29889`):

```python
response_token_ids: [29871, 13, 2277, 29937, 4007, 22137, 29901, 29871]
text_w_context_token_ids: [2023, 1563, 3030, 29889, 13, 2277, 29937, 4007, 22137, 29901, 10428, 3030, 856]
```

Second test ("\n### Assistant:") prints (same problem as above):

```python
response_token_ids: [29871, 13, 2277, 29937, 4007, 22137, 29901]
text_w_context_token_ids: [2023, 1563, 3030, 29889, 13, 2277, 29937, 4007, 22137, 29901, 10428, 3030, 856]
```



Regarding the modified implementation, I did a quick and dirty fix, but it works. It's using directly some token_ids that I'll prepare with enough context and then slice the first token that gets tokenized differently because of lack of context:

```python
import numpy as np
from typing import Any, Dict, List, Optional, Union

class DataCollatorForCompletionOnlyLM(DataCollatorForLanguageModeling):
    def __init__(
        self,
        response_template: Union[str, list],
        tokenizer,
        instruction_template: Optional[str] = None,
        mlm: bool = False,
        ignore_index: int = -100,
        **kwargs,
    ):
        super().__init__(tokenizer=tokenizer, mlm=mlm, **kwargs)
        self.instruction_template = instruction_template
        self.response_template = response_template
        self.ignore_index = ignore_index
        if type(response_template) == list:
            print(f'Using directly token_ids of response_template: {response_template}')
            self.response_token_ids = response_template
        else:
            self.response_token_ids = self.tokenizer.encode(self.response_template, add_special_tokens=False)
```

And I instantiate it like this:

```python
    data_collator = DataCollatorForCompletionOnlyLM(
        tokenizer=tokenizer,
        response_template=tokenizer('\n\n### Assistant:')['input_ids'][2:],
    )
```

It works because I'm creating the `response_template` with the enough context for it to later match the prompt, and I take away (hence the [2:]) the special token and the "\n" without context that gets tokenized differently (and the cause of the problem)

**Comment by ChristianPala** [comment]
I'm having a similar issue fine-tuning llama-2 style with:
```python 
def define_collator(self):
    response_template = "[/INST]"
    return DataCollatorForCompletionOnlyLM(response_template, tokenizer=self.tokenizer)
```
using:
```python
tokenizer = LlamaTokenizer.from_pretrained(self.script_args.model_name)
tokenizer.pad_token = tokenizer.eos_token  # compatible with DataCollatorForCompletionOnlyLM
```

**Comment by ivsanro1** [comment]
> I'm having a similar issue fine-tuning llama-2 style with

If you want, you can try the fix I posted above and if it also works for you I'll create a PR with it :+1:

**Comment by younesbelkada** [comment]
Hi @ivsanro1 
I see the issue, the patch makes sense, would you like to open a PR to fix the issue? 🙏

**Comment by ivsanro1** [comment]
Fixed in https://github.com/lvwerra/trl/pull/622
