### ISSUE TITLE
top_k_top_p_filtering import error

### ISSUE THREAD

**Issue by jesus255221** [lvwerra/trl#6]
Using newer transformers version like 3.0, the top_k_top_p_filtering might fail to import because it is moved to generation_utils

**Comment by lvwerra** [comment]
Thanks for pointing this out. I made a hard dependency to the transformers (2.6.0) library to avoid such issues (see commit 1662d78b5c5e688823b06c69495632abd68b7484). I will upgrade the library to transformers 3.0 at a later time. In the meantime, feel free to create a PR if you have time to test if the library works under transformers 3.0.

To upgrade the library use `pip install trl==0.0.2`.

**Comment by ashokchhetri7** [comment]
So, in the previous code, the top_k_top_p_filtering was imported from the transformers.generation_utils. I changed underscore to . as shown in following and it solved my problem:

`from transformers.generation.utils import top_k_top_p_filtering`

**Comment by Aryan-Deshpande** [comment]
![image](https://github.com/huggingface/trl/assets/72693780/e9065970-0eaa-46a7-90b7-d7a397b0d20c)
After directly installing transformer from its repository.
and using latest version of trl, im still encountering this error

**Comment by polarbeargo** [comment]
Same here I encountered the same error as @Aryan-Deshpande this week. Last week can import SFTTrainer without this error.

**Comment by Aryan-Deshpande** [comment]
I might have found the issue with this, we have to import TrainerArguments from transformers instead.
'from transformers import TrainerArguments' please correct me if i am wrong.

**Comment by polarbeargo** [comment]
No, I already separated import  SFTTrainer and TrainerArguments
![git](https://github.com/huggingface/trl/assets/8589224/3331df79-6d07-4c13-aab0-06ec4b8ad039)

**Comment by dangl00** [comment]
Make sure that you have transformers version 4.38.2 as "top_k_top_p_filtering" is removed in the next version. Then, as previously mentioned by @ashokchhetri7 ,  importing it from"transformers.generation.utils" should work.

**Comment by jstephencorey** [comment]
Changing the transformer version to 4.38.2 did work for me, as well.

**Comment by elyhahami18** [comment]
pip install transformers==4.38.2 worked

**Comment by aseef2289** [comment]
![image](https://github.com/huggingface/trl/assets/100977702/dfe7e5d8-20fb-46e8-a057-880f40637feb)
![image](https://github.com/huggingface/trl/assets/100977702/694705cf-0137-40d2-821f-9987fda56539)
I'm still getting the import error even with transformers==4.38.2

Any idea what could be wrong here?

**Comment by guojunzzc** [comment]
> > pip install transformers==4.38.2 worked for me as well
> 
> ![image](https://private-user-images.githubusercontent.com/100977702/331039223-dfe7e5d8-20fb-46e8-a057-880f40637feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTYwNzksIm5iZiI6MTcxNzMxNTc3OSwicGF0aCI6Ii8xMDA5Nzc3MDIvMzMxMDM5MjIzLWRmZTdlNWQ4LTIwZmItNDZlOC1hMDU3LTg4MGY0MDYzN2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwODA5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjBlYmZjM2JlMGZkMTU5NGQ4M2ZiNWM3NzVkZWQ2MGQwMDkxMzM3OTFmYTMzODA0MDIxZjE1OTk1MzY1MTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jSLfuE7A_a7fnKNhsl5bp5W7qm0yDF9N7RYe-buVRPc) ![image](https://private-user-images.githubusercontent.com/100977702/331039249-694705cf-0137-40d2-821f-9987fda56539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTYwNzksIm5iZiI6MTcxNzMxNTc3OSwicGF0aCI6Ii8xMDA5Nzc3MDIvMzMxMDM5MjQ5LTY5NDcwNWNmLTAxMzctNDBkMi04MjFmLTk5ODdmZGE1NjUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwODA5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmYyYTBlNWJkMTliNzA3MzUyYzdjZTQwYWI0M2JkMDJkYjQ4MjMwYTEwNTJiMDdjZjBlNDY2MTM1NDVkZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JdrgWMmqU30rbffDI2RbZB8Xap4f3W3vSsus0a17a1M) I'm still getting the import error even with transformers==4.38.2
> 
> Any idea what could be wrong here?

from transformers import top_k_top_p_filtering
