### ISSUE TITLE
`token` is not supported for private repos

### ISSUE THREAD

**Issue by ain-soph** [lvwerra/trl#602]
### Reproduce
```python3
import trl
trl.AutoModelForCausalLMWithValueHead.from_pretrained(
    'meta-llama/Llama-2-7b-chat-hf',
    token=TOKEN,

    torch_dtype='auto', low_cpu_mem_usage=True,
    device_map='auto',
)
```

### Reason
In https://github.com/lvwerra/trl/blob/v0.4.7/trl/models/modeling_base.py, `hf_hub_download` is used without passing `token` argument:

https://github.com/lvwerra/trl/blob/d06b131097df1a0ab4283a7031c151cad4fe7396/trl/models/modeling_base.py#L243-L253

### Workaround
Download to local folder first

**Comment by younesbelkada** [comment]
Thanks for the report #604 should resolve the issue, thanks!
