### ISSUE TITLE
SFTTrainer can add <s> and </s> to the text?

### ISSUE THREAD

**Issue by moseshu** [lvwerra/trl#617]
bellow is my preudocode.

my data format is like `
data="[INST] <<SYS>>\nYou are a helpful, respectful and honest assistant.Help as much as you can.\n<</SYS>>\n\n{input} [/INST] {response}"
`
the question is that SFTTrainer can add \<s>  to the start of data or \</s> to the end of data by default?
if SFTTrainer does't add it, I need to add \<s> and \</s> to my data
`
tokenizer = LlamaTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
# Set training parameters
    training_arguments = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=num_epochs,
        per_device_train_batch_size=micro_batch_size,
        gradient_accumulation_steps=4,
        optim="paged_adamw_32bit",
        sharded_ddp=True,
        save_steps=200,
        logging_steps=200,
        learning_rate=learning_rate,
        weight_decay=0.001,
        save_strategy="steps",
        fp16=False,
        bf16=False,
        max_steps = -1,
        evaluation_strategy="steps" if val_set_size > 0 else "no",
        eval_steps=200 if val_set_size > 0 else None,
        max_grad_norm=0.3,
        warmup_ratio=0.03,
        ddp_timeout=3600,
        group_by_length=group_by_length,
        lr_scheduler_type="constant",
        report_to="tensorboard",
        ddp_find_unused_parameters=False,
    )
    formatting_func1 = partial(formatting_prompts_func,prompt="llama2")
    callbacks = [SavePeftModelCallback()]
    # Set supervised fine-tuning parameters
    trainer = SFTTrainer(
        model=model,
        train_dataset=train_data,
        eval_dataset=val_data,
        peft_config=peft_config,
        formatting_func=formatting_func1,
        max_seq_length=cutoff_len,
        tokenizer=tokenizer,
        args=training_arguments,
        packing=packing,
        callbacks=callbacks,
    )
    `

**Comment by lvwerra** [comment]
The dataset is tokenized with:
```python
outputs = tokenizer(
                element[dataset_text_field] if not use_formatting_func else formatting_func(element),
                truncation=True,
                padding=False,
                max_length=max_seq_len,
                return_overflowing_tokens=False,
                return_length=False,
            )
```
You could check if that adds the special tokens for you and otherwise add them in the `formatting_func`. Hope this helps!

**Comment by moseshu** [comment]
> 

thanks
