### ISSUE TITLE
Errors in :gpt2-sentiment-ppo-training.ipynb

### ISSUE THREAD

**Issue by l1f14bscs0388** [lvwerra/trl#71]
Hi, you imorting "from trl.gpt2 import GPT2HeadWithValueModel, respond_to_batch" in "gpt2-sentiment-ppo-training.ipynb" but in trl library we don't have gpt-2 file and i cannot find GPT2HeadWithValueModel in **trl** dirctory. 

advance thanks.

**Comment by younesbelkada** [comment]
Hi, yes we are currently refactoring the repository to make it more accessible for more models & to do distributed training
if you want to use the examples on the notebook please use `trl` from the previous release `pip install trl`
