### ISSUE TITLE
Error in gpt2-sentiment-control.ipynb

### ISSUE THREAD

**Issue by alejandroballestae** [lvwerra/trl#79]
When initializing the PPOTrainer "ppo_trainer = PPOTrainer(gpt2_model, gpt2_model_ref, **config)" The function call is missing the tokenizer as an argument. I suggest to include it as follows "ppo_trainer = PPOTrainer(gpt2_model, gpt2_model_ref, gpt2_tokenizer, **config)"

**Comment by natolambert** [comment]
Should be solved in #80, feel free to re-open if that's not the case.
