### ISSUE TITLE
Automate the downloading of imdb dataset

### ISSUE THREAD

**Issue by zitterbewegung** [lvwerra/trl#8]
Hi, it is sort of a schlep to download the imdb dataset for the example in this library. Would it be better to attempt to automate this download? From my understanding it can be done using transformers also?

!pip install datasets

from datasets import load_dataset
dataset = load_dataset('imdb')
etc...

Or do you think this would be better off not to complicate the examples in the notebook?

**Comment by lvwerra** [comment]
No, this would certainly be a great addition to the notebook. I will have a look at it. In the meantime feel free to create a PR if you implemented it already.
