### ISSUE TITLE
issue with out of data imports in tutorial

### ISSUE THREAD

**Issue by fabianbunbury** [lvwerra/trl#83]
there is a demo https://huggingface.co/docs/trl/sentiment_tuning you are instructed to AutoModelForCausalLMWithValueHead instead of GPT2HeadWithValueModel i believe this is out of data.

**Comment by fabianbunbury** [comment]
Also i apologise if that tutorial has nothing to do with you and is made by some unaffiliated person i'm new to hugging faces.

**Comment by lvwerra** [comment]
Actually the `AutoModel` approach is the new way to do it but it's not yet released. You need to install from `main` branch to use it.
