### ISSUE TITLE
Add google's T5 to models

### ISSUE THREAD

**Issue by cdxzyc** [lvwerra/trl#90]
It will allow to train something similar to chatGPT.

**Comment by younesbelkada** [comment]
This is on the way! 
see https://github.com/lvwerra/trl/pull/75 and https://github.com/younesbelkada/trl/pull/1

**Comment by cdxzyc** [comment]
> This is on the way!
> see #75 and [younesbelkada#1](https://github.com/younesbelkada/trl/pull/1)

Hi, can this branch now run the T5 model correctly?

**Comment by lvwerra** [comment]
We are still working on it and testing it we'll have something in the coming days.

**Comment by lvwerra** [comment]
It is merged now! 🚀
